import AxeBuilder from "@axe-core/playwright";
import { expect, type Page } from "@playwright/test";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface Identity {
  role: string;
  name: string;
  password: string;
}

interface Inventory {
  roles: Record<string, { home: string }>;
  capabilities: Record<string, { roles: string[] }>;
  screens: { id: string; path: string; title: string; capability: string | null }[];
}

// Read straight from the file: the tests must not trust the app's own copy of the access rules.
const inventory: Inventory = JSON.parse(readFileSync(resolve(process.cwd(), "src", "config", "inventory.json"), "utf-8"));

// Generated by infra/platform/keycloak/provision.py, git-ignored; passwords are random per installation.
const identities: Record<string, Identity> = JSON.parse(readFileSync(resolve(process.cwd(), "..", "infra", "platform", "output", "demo_identities.json"), "utf-8"));

export const ROLES = Object.keys(inventory.roles);

export function userFor(role: string, nth = 0): string {
  const found = Object.entries(identities).filter(([, spec]) => spec.role === role);
  const entry = found[nth];
  if (!entry) throw new Error(`no demo user for role ${role}`);
  return entry[0];
}

export const nameOf = (username: string): string => identities[username]!.name;

export async function signIn(page: Page, username: string, from = "/login"): Promise<void> {
  await page.goto(from);
  if (new URL(page.url()).pathname === "/login") await page.getByRole("button", { name: "Sign in" }).click();
  await fillLogin(page, username);
  await page.waitForURL((url) => url.origin === "http://localhost:5173" && url.pathname !== "/callback", { timeout: 30_000 });
  await expect(page.getByTestId("user-name")).toContainText(nameOf(username));
}

/** The identity provider's own sign-in form, filled and submitted. */
export async function fillLogin(page: Page, username: string): Promise<void> {
  await page.locator("#username").fill(username);
  await page.locator("#password").fill(identities[username]!.password);
  await page.locator("#kc-login").click();
}

/** Screens a role should see in the navigation, computed straight from the inventory - not from the app's own code. */
export function expectedNavigation(role: string): string[] {
  const held = new Set(
    Object.entries(inventory.capabilities)
      .filter(([, spec]) => spec.roles.includes(role))
      .map(([capability]) => capability),
  );
  const special = new Set(["login", "forbidden", "session-expired", "not-found"]);
  return inventory.screens
    .filter((screen) => !special.has(screen.id) && !screen.path.includes(":") && (screen.capability === null || held.has(screen.capability)))
    .map((screen) => screen.title)
    .sort();
}

export function homeFor(role: string): { id: string; path: string; title: string } {
  const id = inventory.roles[role]!.home;
  const screen = inventory.screens.find((s) => s.id === id)!;
  return { id, path: screen.path, title: screen.title };
}

export async function expectNoAxeViolations(page: Page, context: string): Promise<void> {
  const results = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "wcag22aa"]).analyze();
  const summary = results.violations.map((v) => `${v.id} (${v.impact}): ${v.nodes.slice(0, 3).map((n) => n.target.join(" ")).join(" | ")}`);
  expect(summary, `axe violations on ${context}`).toEqual([]);
}

function platformEnv(): Record<string, string> {
  const values: Record<string, string> = {};
  const text = readFileSync(resolve(process.cwd(), "..", "infra", "platform", ".env"), "utf-8");
  for (const line of text.split(/\r?\n/)) {
    const at = line.indexOf("=");
    if (at > 0 && !line.trimStart().startsWith("#")) values[line.slice(0, at).trim()] = line.slice(at + 1).trim();
  }
  return values;
}

/** Ends every identity-provider session of a user, as an administrator would - the way "the session ended elsewhere" is produced for real. */
export async function endAllSessions(username: string): Promise<void> {
  const env = platformEnv();
  const base = "http://127.0.0.1:8180";
  const token = await fetch(`${base}/realms/master/protocol/openid-connect/token`, {
    method: "POST",
    body: new URLSearchParams({ grant_type: "password", client_id: "admin-cli", username: env.KEYCLOAK_ADMIN!, password: env.KEYCLOAK_ADMIN_PASSWORD! }),
  }).then((r) => r.json() as Promise<{ access_token: string }>);
  const headers = { Authorization: `Bearer ${token.access_token}` };
  const users = (await fetch(`${base}/admin/realms/aiops/users?username=${encodeURIComponent(username)}&exact=true`, { headers }).then((r) => r.json())) as { id: string }[];
  const response = await fetch(`${base}/admin/realms/aiops/users/${users[0]!.id}/logout`, { method: "POST", headers });
  if (!response.ok) throw new Error(`could not end sessions: ${response.status}`);
}

/** Run one of backend/demo/fixtures.py's commands against the demo database and return what it printed. */
export function fixture<T = Record<string, unknown>>(...args: string[]): T {
  const python = resolve(process.cwd(), "..", "..", ".venv", "Scripts", "python.exe");
  const script = resolve(process.cwd(), "..", "backend", "demo", "fixtures.py");
  const out = execFileSync(python, [script, ...args], { encoding: "utf-8", timeout: 60_000 });
  return JSON.parse(out.trim().split(/\r?\n/).pop() ?? "{}") as T;
}

export interface ScreenSpec {
  id: string;
  path: string;
  title: string;
}

/** The screens a role may open, computed from the inventory file (not the app's own copy). Screens whose path has a parameter are opened from their list. */
export function screensFor(role: string): ScreenSpec[] {
  const held = new Set(
    Object.entries(inventory.capabilities)
      .filter(([, spec]) => spec.roles.includes(role))
      .map(([capability]) => capability),
  );
  const special = new Set(["login", "forbidden", "session-expired", "not-found"]);
  return inventory.screens.filter((s) => !special.has(s.id) && (s.capability === null || held.has(s.capability))).map(({ id, path, title }) => ({ id, path, title }));
}

/** Waits until nothing on the screen is still loading, so a check sees the screen as a person would. */
export async function settled(page: Page): Promise<void> {
  await expect(page.locator(".state-loading")).toHaveCount(0, { timeout: 30_000 });
  await page.waitForTimeout(600);
}

export interface Stop {
  key: string;
  /** Position in the document, so two controls with the same name are not mistaken for one. */
  at: number;
  indicator: boolean;
  visible: boolean;
}

/**
 * Presses Tab `count` times and reports each stop: what has focus, whether a focus indicator is drawn, whether it is on screen.
 * `from: "skip"` starts on the skip link (the first stop of a fresh page); `from: "main"` follows the skip link with Enter, as a
 * keyboard user does, and reports the stops after it. (A page reached through a route change already has focus on its heading.)
 */
export async function tabThrough(page: Page, count: number, from: "skip" | "main" = "skip"): Promise<Stop[]> {
  const read = () =>
    page.evaluate(() => {
      const el = document.activeElement as HTMLElement | null;
      if (!el || el === document.body) return null;
      const style = getComputedStyle(el);
      const rect = el.getBoundingClientRect();
      const name = el.getAttribute("aria-label") ?? (el.textContent ?? "").trim().slice(0, 40);
      return {
        key: `${el.tagName.toLowerCase()}${el.id ? `#${el.id}` : ""}:${name}`,
        at: Array.from(document.querySelectorAll("*")).indexOf(el),
        indicator: (style.outlineStyle !== "none" && parseFloat(style.outlineWidth) > 0) || style.boxShadow !== "none",
        visible: rect.width > 0 && rect.height > 0,
      };
    });
  const stops: Stop[] = [];
  await page.locator(".skip-link").focus();
  if (from === "skip") {
    const first = await read();
    if (first) stops.push(first);
  } else {
    await page.keyboard.press("Enter");
    expect(await page.evaluate(() => document.activeElement?.id), "the skip link moves focus to main").toBe("main");
  }
  for (let i = from === "skip" ? 1 : 0; i < count; i += 1) {
    await page.keyboard.press("Tab");
    const stop = await read();
    if (stop) stops.push(stop);
  }
  return stops;
}

/** Measured numbers a spec wants in the evidence file (`tools/e2e_evidence.py --metrics .metrics/p08_10.json`). Merged per section, so specs can add to it in any order. */
export function recordMetrics(section: string, data: unknown): void {
  const dir = resolve(process.cwd(), ".metrics");
  const file = resolve(dir, "p08_10.json");
  mkdirSync(dir, { recursive: true });
  const current: Record<string, unknown> = existsSync(file) ? JSON.parse(readFileSync(file, "utf-8")) : {};
  current[section] = data;
  writeFileSync(file, JSON.stringify(current, null, 2));
}
