"""P10.06: train, select, evaluate and package the operational anomaly detector.

    python source-code/models/operations_detector/train_evaluate.py            # needs the P10.05 dataset (run-a)

What happens, in order, and what each split is allowed to do:

1. TRAIN (5 seeds) fits every candidate. Unsupervised ones see normal steps only; the supervised one sees the labels.
2. VALIDATION (2 seeds) chooses each candidate's alarm threshold (lowest threshold within the false-alarm budget) and the
   candidate to serve. A learned detector is accepted only if, on validation, it detects more degraded runs than BOTH
   transparent baselines at the same false-alarm budget; otherwise the best baseline is the one served and the model is
   reported as not accepted. Nothing from TEST is used here.
3. TEST (2 seeds) is opened exactly once for the final comparison (`test_split_ledger.json`), every candidate at the
   threshold validation chose, and only reported.
4. Scoring latency of the served detector is measured on one live window at a time, and the live scoring path is checked
   against batch scoring of the same data.
5. The package (`models/registry/ops-anomaly-detector/1.0.0/`) records model, thresholds, provenance, metrics, latency and
   limitations. The fitted model file is git-ignored (like every trained artefact here) and regenerated by this script; its
   sha256 and the dataset hash are in the committed manifest.
"""

from __future__ import annotations

import hashlib
import json
import platform
import sys
import time
from datetime import UTC, datetime
from pathlib import Path

import joblib
import numpy as np
import scipy
import sklearn

SOURCE_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(SOURCE_ROOT))

from models.evaluation.test_gate import record_opening  # noqa: E402
from models.operations_detector.detectors import (  # noqa: E402
    Prepared,
    fit_fill,
    fit_scale,
    make_detectors,
)
from models.operations_detector.evaluate import (  # noqa: E402
    FALSE_ALARM_BUDGET_PER_HOUR,
    PERSISTENCE,
    score_run,
    select_threshold,
    summarise,
)
from models.operations_detector.features import (  # noqa: E402
    DATASET_ROOT,
    FEATURE_NAMES,
    FEATURE_VERSION,
    HISTORY,
    SIGNAL_NAMES,
    STEP_S,
    load_split,
)
from models.operations_detector.runtime import OperationsDetector  # noqa: E402

HERE = Path(__file__).resolve().parent
PACKAGE = SOURCE_ROOT / "models" / "registry" / "ops-anomaly-detector" / "1.0.0"
SLO_FIXED_THRESHOLD = 1.0
SEED = 20260925


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def code_hashes() -> dict[str, str]:
    files = [
        HERE / n
        for n in ("features.py", "detectors.py", "evaluate.py", "runtime.py", "train_evaluate.py")
    ]
    files.append(SOURCE_ROOT / "models" / "operations_dataset" / "signals.py")
    return {p.name: sha256_file(p) for p in files}


def run_all(prepared: list[Prepared], det, threshold: float) -> tuple[list, dict]:
    scores = [det.score(p) for p in prepared]
    results = [score_run(p, s, threshold) for p, s in zip(prepared, scores, strict=True)]
    return results, summarise(results)


def latency_ms(detector, fill: np.ndarray, sample: Prepared) -> dict:
    """One live window at a time: the newest step's score from the last HISTORY raw rows, end to end."""
    live = OperationsDetector(
        {"detector": detector, "fill": fill, "threshold": 0.0, "feature_version": FEATURE_VERSION},
        {},
    )
    windows = [
        sample.run.raw[i - HISTORY + 1 : i + 1]
        for i in sample.index[:: max(1, len(sample.index) // 300)]
    ]
    for w in windows[:20]:
        live.score(w)
    times = []
    for _ in range(5):
        for w in windows:
            t0 = time.perf_counter()
            live.score(w)
            times.append((time.perf_counter() - t0) * 1000.0)
    return {
        "samples": len(times),
        "p50_ms": float(np.percentile(times, 50)),
        "p95_ms": float(np.percentile(times, 95)),
        "p99_ms": float(np.percentile(times, 99)),
        "max_ms": float(max(times)),
    }


def live_batch_parity(detector, fill: np.ndarray, prepared: list[Prepared]) -> dict:
    live = OperationsDetector(
        {"detector": detector, "fill": fill, "threshold": 0.0, "feature_version": FEATURE_VERSION},
        {},
    )
    diffs = []
    for p in prepared[:12]:
        batch = detector.score(p)
        for k in range(0, len(p.index), 4):
            i = p.index[k]
            window = p.run.raw[i - HISTORY + 1 : i + 1]
            diffs.append(abs(live.score(window) - batch[k]))
    return {
        "windows": len(diffs),
        "max_abs_difference": float(max(diffs)),
        "median_abs_difference": float(np.median(diffs)),
    }


def main() -> int:
    manifest = json.loads(
        (DATASET_ROOT / "run-a" / "dataset_manifest.json").read_text(encoding="utf-8")
    )
    dataset_sha = manifest["dataset_sha256"]
    train_runs, val_runs, test_runs = (load_split(s) for s in ("train", "validation", "test"))
    fill = fit_fill(train_runs)
    scale = fit_scale(train_runs, fill)
    train, val, test = (
        [Prepared(r, fill) for r in runs] for runs in (train_runs, val_runs, test_runs)
    )
    print(
        f"runs: train {len(train)}, validation {len(val)}, test {len(test)}; dataset {dataset_sha[:16]}",
        flush=True,
    )

    detectors = make_detectors()
    fitted, thresholds, validation = {}, {}, {}
    for det in detectors:
        started = time.time()
        det.fit(train)
        val_scores = [det.score(p) for p in val]
        if det.name == "slo_thresholds":
            threshold = SLO_FIXED_THRESHOLD
            results = [score_run(p, s, threshold) for p, s in zip(val, val_scores, strict=True)]
            summary = summarise(results)
        else:
            threshold, summary = select_threshold(val, val_scores)
        fitted[det.name], thresholds[det.name], validation[det.name] = det, threshold, summary
        print(
            f"  {det.name:18} threshold {threshold:9.4f}  validation recall {summary['event_recall']:.2f}  "
            f"false alarms/h {summary['false_alarms_per_hour']:.2f}  ({time.time() - started:.0f} s)",
            flush=True,
        )

    # ---- choose what to serve, on validation only
    learned = [n for n in ("isolation_forest", "gradient_boosting")]
    baseline_best = max(
        ("slo_thresholds", "robust_zscore"),
        key=lambda n: (
            validation[n]["event_recall"],
            -(validation[n]["false_alarms_per_hour"] or 0),
        ),
    )
    choice = max(
        learned,
        key=lambda n: (
            validation[n]["event_recall"],
            -(validation[n]["false_alarms_per_hour"] or 0),
        ),
    )
    within_budget = lambda n: validation[n]["false_alarms_per_hour"] <= FALSE_ALARM_BUDGET_PER_HOUR  # noqa: E731
    beats = all(
        validation[choice]["event_recall"] > validation[b]["event_recall"] or not within_budget(b)
        for b in ("slo_thresholds", "robust_zscore")
    ) and within_budget(choice)
    served = choice if beats else baseline_best
    print(
        f"candidate {choice}, best baseline {baseline_best}: model {'ACCEPTED' if beats else 'NOT accepted'}; serving {served}",
        flush=True,
    )

    # ---- the one opening of the test split
    record_opening(
        "final_comparison",
        dataset_sha,
        FEATURE_VERSION,
        {
            "model_id": "ops-anomaly-detector",
            "model_version": "1.0.0",
            "selected_candidate": served,
            "selected_on": "validation",
        },
    )
    test_results: dict[str, dict] = {}
    for name, det in fitted.items():
        _, summary = run_all(test, det, thresholds[name])
        test_results[name] = summary
        print(
            f"  TEST {name:18} recall {summary['event_recall']:.2f} {tuple(round(x, 2) for x in summary['event_recall_wilson95'])}  "
            f"false alarms/h {summary['false_alarms_per_hour']:.2f}  median delay {summary['median_delay_s']} s",
            flush=True,
        )

    # ---- severity breakdown of the served detector on test (how weak a fault does it still catch?)
    results, _ = run_all(test, fitted[served], thresholds[served])
    faulty = sorted((r for r in results if r.detected is not None), key=lambda r: r.severity)
    thirds = np.array_split(np.arange(len(faulty)), 3)
    by_severity = {
        label: {
            "severity_range": [round(faulty[g[0]].severity, 2), round(faulty[g[-1]].severity, 2)],
            "runs": len(g),
            "detected": sum(1 for i in g if faulty[i].detected),
        }
        for label, g in zip(
            ("mildest_third", "middle_third", "most_severe_third"), thirds, strict=True
        )
    }

    latency = latency_ms(fitted[served], fill, test[0])
    parity = live_batch_parity(fitted[served], fill, test)
    print(
        f"latency p95 {latency['p95_ms']:.2f} ms; live/batch max diff {parity['max_abs_difference']:.2e}",
        flush=True,
    )

    # ---- package
    PACKAGE.mkdir(parents=True, exist_ok=True)
    joblib.dump(
        {
            "detector": fitted[served],
            "fill": fill,
            "scale": scale,
            "threshold": thresholds[served],
            "feature_version": FEATURE_VERSION,
        },
        PACKAGE / "model.joblib",
    )
    evaluation = {
        "validation": validation,
        "test": test_results,
        "thresholds": thresholds,
        "served_detector": served,
        "candidate_model": choice,
        "best_baseline": baseline_best,
        "candidate_model_accepted": bool(beats),
        "served_by_severity_on_test": by_severity,
        "latency": latency,
        "live_batch_parity": parity,
    }
    (PACKAGE / "evaluation.json").write_text(
        json.dumps(evaluation, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    train_steps = int(sum(len(p.index) for p in train))
    card = {
        "model_id": "ops-anomaly-detector",
        "model_version": "1.0.0",
        "purpose": "flag degraded platform behaviour (stream, API and freshness signals) from Prometheus-derived signals",
        "served_detector": served,
        "feature_version": FEATURE_VERSION,
        "signals": list(SIGNAL_NAMES),
        "step_seconds": STEP_S,
        "history_steps": HISTORY,
        "features": list(FEATURE_NAMES),
        "alarm_rule": f"score >= threshold for {PERSISTENCE} consecutive steps ({PERSISTENCE * STEP_S} s)",
        "threshold": thresholds[served],
        "threshold_selection": f"lowest validation threshold with at most {FALSE_ALARM_BUDGET_PER_HOUR} false-alarm episodes per hour outside fault windows",
        "selection_rule": "a learned candidate is served only if on validation it detects more degraded runs than both transparent baselines within the false-alarm budget",
        "provenance": {
            "dataset_sha256": dataset_sha,
            "dataset": "models/operations_dataset/output/run-a (P10.05)",
            "splits": manifest["splits"],
            "train_runs": len(train),
            "validation_runs": len(val),
            "test_runs": len(test),
            "train_scored_steps": train_steps,
            "random_seed": SEED,
            "trained_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "python": platform.python_version(),
            "scikit_learn": sklearn.__version__,
            "numpy": np.__version__,
            "scipy": scipy.__version__,
            "code_sha256": code_hashes(),
            "test_split_opened": "once, purpose final_comparison, recorded in models/registry/test_split_ledger.json",
        },
        "limitations": [
            "Trained and tested on a synthetic seeded load driving the platform's real instruments; no production traffic was recorded.",
            "Six fault types on the stream, API and freshness signals only; device, storage, certificate and configuration faults are covered by the P10.04 alert rules, not by this model.",
            "Fault magnitudes were drawn from fixed ranges; a fault milder than the mildest training severity may go undetected (see the severity breakdown).",
            "Test set is 2 seeds x 2 replicates per scenario: recall intervals are wide and are reported, not hidden.",
            "One host, one Prometheus version, 5 s step, 30 s rate windows: a different scrape or push cadence needs re-validation.",
            "The score says 'this looks unlike normal or like a known fault', never why; correlation and any cause hypothesis are P10.07 and are labelled unverified.",
        ],
    }
    (PACKAGE / "model_card.json").write_text(
        json.dumps(card, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    files = {
        n: sha256_file(PACKAGE / n) for n in ("model.joblib", "evaluation.json", "model_card.json")
    }
    (PACKAGE / "artifact_manifest.json").write_text(
        json.dumps(
            {
                "format": "ops-anomaly-detector-package/1",
                "files": files,
                "dataset_sha256": dataset_sha,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"package written to {PACKAGE}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
