"""P09.07: the source of truth for how the platform's controls line up against security, privacy and AI frameworks.

    python source-code/security/framework_mapping.py            # rewrite framework_mapping.json
    python source-code/security/framework_mapping.py --check    # fail if the JSON on disk is not what this file produces

This file holds the mapping (which controls and documents stand behind which framework item, who owns it, what is missing);
`verify_control_mapping.py` checks it against the real control catalogue, evidence and register, and renders the tables in
`docs/security/CONTROL_MAPPING.md`.

WHAT THIS IS NOT. It is a mapping and a gap list for an academic prototype. It is not an assessment against any framework and
makes no claim of compliance, conformity or certification with any of them (ISO/IEC 27001, NIST CSF, ETSI EN 303 645, IEC 62443,
OWASP ASVS, NIST AI RMF, ISO/IEC 42001, GDPR). A framework item lists what the platform does that relates to it and what evidence
exists; the standard's own wording, scope and audit rules are not applied here. GDPR and the EU AI Act are legal questions for
qualified counsel; nothing here is legal advice.

Coverage is COMPUTED from the controls the item cites, never written down:

    evidenced     every cited control is `implemented` (its evidence passes today)
    partial       at least one cited control is implemented or partial, and something is missing
    documented    no control cited, but a document records the intent (intent, not enforcement)
    gap           applicable, and neither a working control nor a document exists (or only planned controls do)
    out_of_scope  not applicable to a software prototype with no operating organisation, staff or premises (reason given)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "framework_mapping.json"

STATEMENT = (
    "A mapping and gap list for an academic prototype. It makes no claim of compliance, conformity or certification with any framework "
    "named here, applies none of their audit rules, and is not legal advice."
)

SEC = "docs/SECURITY_COMPLIANCE_BASELINE.md"
TM = "docs/security/THREAT_MODEL.md"
RR = "docs/security/RISK_REGISTER.md"
ARCH = "docs/security/SECURITY_ARCHITECTURE.md"
ROLES = "docs/security/ROLES_AND_ACTION_AUTHORITY.md"
DPIA = "docs/security/DATA_INVENTORY_AND_DPIA.md"
PROTO = "docs/PROTOCOLS_AND_STANDARDS.md"
GIT = "docs/environment/GIT_POLICY.md"
BUDGET = "docs/environment/RESOURCE_BUDGET.md"
SLOS = "docs/observability/SLOS_AND_TOPOLOGY.md"
ACCEPT = "docs/requirements/ACCEPTANCE_TARGETS.md"
AIOPS = "source-code/backend/aiops/README.md"
ACCESS = "docs/security/ACCESS_REVIEW.md"
BREACH_RUNBOOK = "docs/runbooks/INCIDENT_RESPONSE_AND_BREACH_RUNBOOK.md"

NOT_ORG = "The control concerns an operating organisation; this prototype has none."
NOT_PEOPLE = (
    "A human-resources control; the prototype has no staff to screen, contract or discipline."
)
NOT_PHYSICAL = "A physical-premises control; the prototype runs on a development host and one lab host it does not own the premises of."


def it(ref: str, title: str, applies: str, controls: tuple[str, ...] = (), docs: tuple[str, ...] = (), note: str = "",
       owner: str = "GRC", next_task: str | None = None, accepted: str | None = None) -> dict:  # fmt: skip
    return {
        "ref": ref, "title": title, "applicability": applies, "controls": list(controls), "docs": list(docs),
        "note": note, "owner": owner, "next": next_task, "accepted": accepted,
    }  # fmt: skip


def out(ref: str, title: str, why: str, owner: str = "GRC") -> dict:
    return it(ref, title, "not_applicable", note=why, owner=owner)


# ------------------------------------------------------------------------------------------ ISO/IEC 27001:2022 Annex A
ISO = [
    it(
        "5.1",
        "Policies for information security",
        "partly",
        docs=(SEC, ARCH),
        note="The baseline and security architecture stand in for a policy set; nothing is management-approved.",
        accepted="A prototype has no management to approve a policy set.",
    ),
    it(
        "5.2",
        "Information security roles and responsibilities",
        "applies",
        ("CTL-05", "CTL-46"),
        (ROLES,),
        "Roles and action authority are finalised; every control has a named owner role.",
        "SEC",
    ),
    it(
        "5.3",
        "Segregation of duties",
        "applies",
        ("CTL-05", "CTL-07", "CTL-21"),
        (ROLES,),
        "Requester is never the approver; the executor and the verifier are independent identities.",
        "SEC",
    ),
    out("5.4", "Management responsibilities", NOT_ORG),
    out("5.5", "Contact with authorities", NOT_ORG),
    out("5.6", "Contact with special interest groups", NOT_ORG),
    it(
        "5.7",
        "Threat intelligence",
        "partly",
        docs=(TM,),
        note="The threat model is built from public framework knowledge; no threat-intelligence feed is consumed.",
        accepted="No feed is available to an academic prototype.",
    ),
    it(
        "5.8",
        "Information security in project management",
        "applies",
        docs=("TASK_REGISTER.md", TM),
        note="Security work is registered tasks with acceptance and evidence; the phase 09 gate exists.",
        owner="SEC",
    ),
    it(
        "5.9",
        "Inventory of information and other associated assets",
        "applies",
        docs=(DPIA, TM),
        note="Data inventory (7 categories) and asset list in the threat model.",
        owner="GRC",
    ),
    it(
        "5.10",
        "Acceptable use of information and other associated assets",
        "partly",
        ("CTL-40",),
        (ROLES,),
        "Roles bound what each identity may do; no acceptable-use policy for people exists.",
        "SEC",
        accepted="No staff to bind.",
    ),
    out("5.11", "Return of assets", NOT_PEOPLE),
    it(
        "5.12",
        "Classification of information",
        "applies",
        ("CTL-16", "CTL-19"),
        (DPIA,),
        "Privacy classification is a contract field on every observation; retention classes are enforced.",
        "GRC",
    ),
    it(
        "5.13",
        "Labelling of information",
        "applies",
        ("CTL-10",),
        (DPIA,),
        "Every event carries a truth label and a privacy classification, validated at ingestion.",
        "DATA",
    ),
    it(
        "5.14",
        "Information transfer",
        "applies",
        ("CTL-09", "CTL-11", "CTL-43"),
        (ARCH,),
        "Device mTLS, TLS to the database, code-plus-PKCE in the browser; Kafka, OPA and Keycloak links are still plain inside the platform network.",
        "SEC",
    ),
    it(
        "5.15",
        "Access control",
        "applies",
        ("CTL-03", "CTL-04", "CTL-05", "CTL-47"),
        (ROLES,),
        "Default-deny endpoint authorization from one inventory; OPA as decision point.",
        "SEC",
    ),
    it(
        "5.16",
        "Identity management",
        "applies",
        ("CTL-02", "CTL-12", "CTL-46"),
        (ACCESS,),
        "Keycloak for people, workload identity for services; the joiner-mover-leaver procedure is in `docs/security/ACCESS_REVIEW.md`.",
        "SEC",
    ),
    it(
        "5.17",
        "Authentication information",
        "applies",
        ("CTL-14", "CTL-43"),
        (),
        "Secrets generated at deployment, kept out of Git and rotated; the token never touches storage in the browser.",
        "SEC",
    ),
    it(
        "5.18",
        "Access rights",
        "applies",
        ("CTL-05", "CTL-46"),
        (ACCESS,),
        "Roles are provisioned from one place; a reviewable report of who holds what is generated.",
        "GRC",
    ),
    it(
        "5.19",
        "Information security in supplier relationships",
        "partly",
        ("CTL-27", "CTL-29"),
        (SEC,),
        "Dependencies and images pinned and signed; no supplier agreements exist for open-source components.",
        "DEVOPS",
        accepted="Open-source suppliers offer no agreements to negotiate.",
    ),
    it(
        "5.20",
        "Addressing information security within supplier agreements",
        "not_applicable",
        note="No supplier agreements exist for the open-source components and free hosted services used.",
    ),
    it(
        "5.21",
        "Managing information security in the ICT supply chain",
        "applies",
        ("CTL-27", "CTL-28", "CTL-29"),
        (),
        "Pinned locks, secret/dependency/image scanning in CI, SBOM, provenance and signing.",
        "DEVOPS",
    ),
    it(
        "5.22",
        "Monitoring, review and change management of supplier services",
        "partly",
        ("CTL-28",),
        (),
        "CI re-scans on every change; no periodic supplier review.",
        "DEVOPS",
        accepted="No supplier agreements to review.",
    ),
    it(
        "5.23",
        "Information security for use of cloud services",
        "partly",
        ("CTL-28",),
        (GIT,),
        "GitHub Actions, Docker Hub and SonarQube Cloud are used with least-privilege tokens; no cloud-service risk assessment is recorded.",
        "DEVOPS",
        next_task="P13.05",
    ),
    it(
        "5.24",
        "Information security incident management planning and preparation",
        "partly",
        ("CTL-15", "CTL-42"),
        (AIOPS,),
        "Platform incidents are correlated and recorded with an append-only history (P10.07); no human incident-response procedure is exercised.",
        "OPS",
        next_task="P13.04",
    ),
    it(
        "5.25",
        "Assessment and decision on information security events",
        "applies",
        ("CTL-15", "CTL-42", "CTL-48"),
        (AIOPS,),
        "Alerts (P10.04) become incidents with severity and an unverified hypothesis (P10.07).",
        "OPS",
    ),
    it(
        "5.26",
        "Response to information security incidents",
        "partly",
        ("CTL-38", "CTL-21"),
        (AIOPS,),
        "Bounded, policy-controlled remediation with escalation to a person (P10.08); no security-incident playbook beyond it.",
        "OPS",
        next_task="P13.04",
    ),
    it(
        "5.27",
        "Learning from information security incidents",
        "partly",
        ("CTL-15",),
        (),
        "Incident and remediation histories are kept append-only; no post-incident review process is run.",
        "OPS",
        accepted="No operating history to learn from.",
    ),
    it(
        "5.28",
        "Collection of evidence",
        "applies",
        ("CTL-15", "CTL-16", "CTL-17"),
        (),
        "Tamper-evident hash-chained histories, redacted exports for the auditor role only.",
        "SEC",
    ),
    it(
        "5.29",
        "Information security during disruption",
        "partly",
        ("CTL-23", "CTL-41", "CTL-06"),
        (),
        "Safe local behaviour on loss of central services; durable edge outbox; policy outage never approves.",
        "SEC",
    ),
    it(
        "5.30",
        "ICT readiness for business continuity",
        "partly",
        ("CTL-35", "CTL-41"),
        (),
        "A tested, encrypted backup and a real disaster restore exist (P11.05: RTO 203 s and RPO 2.3 s on a small data set); there is no scheduled or off-host backup; the edge buffers offline.",
        "DEVOPS",
    ),
    it(
        "5.31",
        "Legal, statutory, regulatory and contractual requirements",
        "partly",
        docs=(DPIA, SEC),
        note="Requirements are identified as GDPR-oriented assumptions; no legal determination is made.",
        accepted="A legal question for qualified counsel, outside the prototype.",
    ),
    it(
        "5.32",
        "Intellectual property rights",
        "applies",
        docs=(GIT,),
        note="Licences and attribution are reviewed in P13.05; only redistributable data is used.",
        next_task="P13.05",
    ),
    it(
        "5.33",
        "Protection of records",
        "applies",
        ("CTL-15", "CTL-18"),
        (),
        "Audit classes are never purged; retention per class is enforced.",
        "GRC",
    ),
    it(
        "5.34",
        "Privacy and protection of PII",
        "applies",
        ("CTL-16", "CTL-18", "CTL-19"),
        (DPIA,),
        "Minimisation at the edge, redaction, retention, role-limited evidence; DPIA-style review.",
        "GRC",
    ),
    it(
        "5.35",
        "Independent review of information security",
        "partly",
        docs=(TM,),
        note="P09.10 and the runs on the target (P11.04, P09.09) are independent acceptance runs and phase 12 adds more; no external review exists.",
    ),
    it(
        "5.36",
        "Compliance with policies, rules and standards for information security",
        "partly",
        ("CTL-28",),
        (),
        "CI gates and the verifiers check the platform's own rules; no external standard is applied.",
        "QA",
        accepted="No claim against any external standard is made or intended.",
    ),
    it(
        "5.37",
        "Documented operating procedures",
        "partly",
        docs=(BUDGET, "docs/environment/CLEAN_START.md"),
        note="Clean-start and resource instructions exist; operational runbooks are P13.04.",
        owner="DEVOPS",
        next_task="P13.04",
    ),
    # ---- 6 people
    out("6.1", "Screening", NOT_PEOPLE),
    out("6.2", "Terms and conditions of employment", NOT_PEOPLE),
    out("6.3", "Information security awareness, education and training", NOT_PEOPLE),
    out("6.4", "Disciplinary process", NOT_PEOPLE),
    it(
        "6.5",
        "Responsibilities after termination or change of employment",
        "partly",
        ("CTL-46",),
        (ACCESS,),
        "The leaver and mover steps for operating roles are written (`ACCESS_REVIEW.md`); no employment exists to change.",
        "GRC",
        accepted="Applies to role holders only.",
    ),
    out("6.6", "Confidentiality or non-disclosure agreements", NOT_PEOPLE),
    out("6.7", "Remote working", NOT_PEOPLE),
    it(
        "6.8",
        "Information security event reporting",
        "partly",
        ("CTL-42",),
        (AIOPS,),
        "Platform events are alerted and correlated; no route exists for people to report events.",
        "OPS",
        next_task="P13.04",
    ),
    # ---- 7 physical
    out("7.1", "Physical security perimeters", NOT_PHYSICAL),
    out("7.2", "Physical entry", NOT_PHYSICAL),
    out("7.3", "Securing offices, rooms and facilities", NOT_PHYSICAL),
    out("7.4", "Physical security monitoring", NOT_PHYSICAL),
    out("7.5", "Protecting against physical and environmental threats", NOT_PHYSICAL),
    out("7.6", "Working in secure areas", NOT_PHYSICAL),
    out("7.7", "Clear desk and clear screen", NOT_PHYSICAL),
    out("7.8", "Equipment siting and protection", NOT_PHYSICAL),
    out("7.9", "Security of assets off-premises", NOT_PHYSICAL),
    out("7.10", "Storage media", NOT_PHYSICAL),
    out("7.11", "Supporting utilities", NOT_PHYSICAL),
    out("7.12", "Cabling security", NOT_PHYSICAL),
    out("7.13", "Equipment maintenance", NOT_PHYSICAL),
    out("7.14", "Secure disposal or re-use of equipment", NOT_PHYSICAL),
    # ---- 8 technological
    out(
        "8.1",
        "User endpoint devices",
        "Operators use a browser; the console holds the token in memory only (CTL-43) but no endpoint is managed.",
    ),
    it(
        "8.2",
        "Privileged access rights",
        "applies",
        ("CTL-05", "CTL-34", "CTL-46"),
        (),
        "The only override (incident commander, SC-2) needs a justification and is audited; roles are reviewed.",
        "SEC",
    ),
    it(
        "8.3",
        "Information access restriction",
        "applies",
        ("CTL-03", "CTL-04", "CTL-17"),
        (),
        "Default-deny per endpoint; the audit trail is readable by the auditor role only.",
        "SEC",
    ),
    it(
        "8.4",
        "Access to source code",
        "partly",
        ("CTL-28",),
        (GIT,),
        "A private GitHub repository with least-privilege CI tokens.",
        "DEVOPS",
        accepted="Single-developer repository.",
    ),
    it(
        "8.5",
        "Secure authentication",
        "applies",
        ("CTL-01", "CTL-02", "CTL-43"),
        (),
        "PKCE S256 only, strict token validation, lockout; MFA readiness is a Keycloak setting not enabled for the demo.",
        "SEC",
    ),
    it(
        "8.6",
        "Capacity management",
        "partly",
        ("CTL-18", "CTL-37"),
        (BUDGET, SLOS),
        "Resource budget, storage and retention alerts (P10.04); load, a measured ceiling and a 30-minute soak on the target (P11.06); no longer soak and no capacity plan.",
        "OPS",
    ),
    it(
        "8.7",
        "Protection against malware",
        "partly",
        ("CTL-28", "CTL-31"),
        (),
        "Image and dependency scanning, non-root read-only edge container; no endpoint anti-malware.",
        "DEVOPS",
        accepted="Container scanning is the relevant surface.",
    ),
    it(
        "8.8",
        "Management of technical vulnerabilities",
        "applies",
        ("CTL-27", "CTL-28", "CTL-29"),
        (),
        "Trivy on the repository and images in CI, pinned dependencies, SBOM.",
        "DEVOPS",
    ),
    it(
        "8.9",
        "Configuration management",
        "applies",
        ("CTL-27", "CTL-37"),
        (SLOS,),
        "Pinned images and locks; configuration and migration drift alerts (P10.04).",
        "DEVOPS",
    ),
    it(
        "8.10",
        "Information deletion",
        "applies",
        ("CTL-18",),
        (DPIA,),
        "Retention windows per class, aggregation before deletion.",
        "GRC",
    ),
    it(
        "8.11",
        "Data masking",
        "applies",
        ("CTL-16", "CTL-19"),
        (),
        "Recursive redaction in audit, logs and errors; privacy-zone suppression at the edge.",
        "SEC",
    ),
    it(
        "8.12",
        "Data leakage prevention",
        "partly",
        ("CTL-16", "CTL-17", "CTL-37"),
        (),
        "Redaction and role-limited evidence; no network-level leakage prevention.",
        "SEC",
        accepted="Out of scope for a single-host prototype.",
    ),
    it(
        "8.13",
        "Information backup",
        "applies",
        ("CTL-35",),
        (),
        "An encrypted, tested backup and a real restore exist (P11.05); a schedule, an off-host copy and custody of the key do not.",
        "DEVOPS",
    ),
    it(
        "8.14",
        "Redundancy of information processing facilities",
        "applies",
        ("CTL-41",),
        (),
        "One node and one volume per store: nothing is redundant beyond the edge outbox, the broker's queue for the gateway and safe local behaviour; what happens in an outage of each component was measured (P11.05, P11.06).",
        "DEVOPS",
        accepted="Accepted for the laboratory: a single node is the scope of this project (docs/environment/RESOURCE_BUDGET.md); redundancy would be a different deployment.",
    ),
    it(
        "8.15",
        "Logging",
        "applies",
        ("CTL-15", "CTL-16", "CTL-36", "CTL-37"),
        (),
        "Append-only audit and transition histories, redacted; time source partly consolidated.",
        "SEC",
    ),
    it(
        "8.16",
        "Monitoring activities",
        "applies",
        ("CTL-37", "CTL-38", "CTL-42"),
        (AIOPS, SLOS),
        "27 alert rules tested live, platform incident correlation, bounded remediation; model drift monitoring is not built.",
        "OPS",
    ),
    it(
        "8.17",
        "Clock synchronization",
        "applies",
        ("CTL-36",),
        (),
        "The database clock stamps every audit row; the target host's time synchronization is neither configured by this deployment nor monitored.",
        "DEVOPS",
    ),
    out(
        "8.18",
        "Use of privileged utility programs",
        "No privileged utilities are exposed by the platform; the host is a development machine.",
    ),
    it(
        "8.19",
        "Installation of software on operational systems",
        "partly",
        ("CTL-29",),
        (),
        "Only signed, provenance-attested artefacts are admitted by the release gate, and on the target the backend and frontend images that run are shown to be the signed ones (P11.03); the edge image is built on the host.",
        "DEVOPS",
    ),
    it(
        "8.20",
        "Networks security",
        "applies",
        ("CTL-09", "CTL-11", "CTL-13"),
        (),
        "Device mTLS with topic ACLs, TLS to the database, and default-deny network policy enforced on a real cluster with 19 positive and negative checks (P11.04); links between services inside the namespace are plain.",
        "SEC",
    ),
    it(
        "8.21",
        "Security of network services",
        "partly",
        ("CTL-11", "CTL-33"),
        (),
        "TLS on the broker and the database and rate limits at the API; the other service links are plain (CTL-11).",
        "SEC",
    ),
    it(
        "8.22",
        "Segregation of networks",
        "partly",
        ("CTL-13", "CTL-08"),
        (ARCH,),
        "Trust zones TZ0-TZ8 are designed; on the cluster the NetworkPolicies were shown to isolate workloads, including a pod of another namespace from the database (P11.04).",
        "SEC",
    ),
    out("8.23", "Web filtering", "No user web browsing is provided by the platform."),
    it(
        "8.24",
        "Use of cryptography",
        "applies",
        ("CTL-09", "CTL-11", "CTL-14", "CTL-29"),
        (),
        "TLS 1.3 to the database, mTLS to devices, signed artefacts, rotated secrets; no key-management service.",
        "SEC",
    ),
    it(
        "8.25",
        "Secure development life cycle",
        "applies",
        ("CTL-28",),
        (GIT,),
        "Registered tasks, tests, verifiers with evidence, CI gates.",
        "DEVOPS",
    ),
    it(
        "8.26",
        "Application security requirements",
        "applies",
        ("CTL-32", "CTL-33"),
        (TM,),
        "Closed schemas, validated inputs, headers, rate limits.",
        "BACKEND",
    ),
    it(
        "8.27",
        "Secure system architecture and engineering principles",
        "applies",
        ("CTL-03", "CTL-04", "CTL-08", "CTL-22"),
        (ARCH,),
        "Default-deny, least privilege, fail closed, separation of demo control.",
        "ARCH",
    ),
    it(
        "8.28",
        "Secure coding",
        "applies",
        ("CTL-28", "CTL-32"),
        (),
        "SonarQube Cloud, secret scanning and tests on every push.",
        "DEVOPS",
    ),
    it(
        "8.29",
        "Security testing in development and acceptance",
        "partly",
        ("CTL-28",),
        (),
        "Negative tests sit beside the positive ones in every verifier; the abuse-case acceptance run (P09.10) and the native checks on the target (P11.04) are done; CI has not yet run on a hosted runner.",
        "QA",
        next_task="P01.05",
    ),
    out("8.30", "Outsourced development", "Development is not outsourced."),
    it(
        "8.31",
        "Separation of development, test and production environments",
        "partly",
        ("CTL-08",),
        (),
        "Scratch databases for verifiers; demo control cannot reach operations; no production exists.",
        "DEVOPS",
        accepted="A prototype has no production environment.",
    ),
    it(
        "8.32",
        "Change management",
        "partly",
        ("CTL-25", "CTL-28"),
        (GIT,),
        "Every change goes through CI; model changes through verify-then-commit activation; no change board.",
        "DEVOPS",
        accepted="Single-developer project.",
    ),
    it(
        "8.33",
        "Test information",
        "applies",
        ("CTL-26", "CTL-40"),
        (DPIA,),
        "All test and training data is synthetic or open; no production personal data exists.",
        "DATA",
    ),
    out(
        "8.34",
        "Protection of information systems during audit testing",
        "No independent audit testing is performed; verifiers run against scratch databases.",
    ),
]

# ------------------------------------------------------------------------------------------------- NIST CSF 2.0
CSF = [
    it(
        "GV.OC",
        "Organizational Context",
        "partly",
        docs=(SEC, PROTO),
        note="Mission, safety boundary and stakeholder assumptions are documented.",
        owner="LEAD",
        accepted="No operating organisation.",
    ),
    it(
        "GV.RM",
        "Risk Management Strategy",
        "applies",
        docs=(RR, TM),
        note="Risk register with likelihood, impact, treatment, owner and residual risk computed from control state.",
        owner="SEC",
    ),
    it(
        "GV.RR",
        "Roles, Responsibilities, and Authorities",
        "applies",
        ("CTL-05", "CTL-46"),
        (ROLES,),
        "Roles and action authority; control owners.",
        "SEC",
    ),
    it(
        "GV.PO",
        "Policy",
        "partly",
        ("CTL-04",),
        (SEC,),
        "Policy is code (OPA) for actions and endpoints; no management policy set.",
        "SEC",
        accepted="No management to approve policies.",
    ),
    it(
        "GV.OV",
        "Oversight",
        "partly",
        ("CTL-15", "CTL-17"),
        (),
        "Auditor role with redacted evidence access.",
        "SEC",
    ),
    it(
        "GV.SC",
        "Cybersecurity Supply Chain Risk Management",
        "applies",
        ("CTL-27", "CTL-28", "CTL-29"),
        (),
        "Locks, digests, scanning, SBOM, provenance, signing.",
        "DEVOPS",
    ),
    it(
        "ID.AM",
        "Asset Management",
        "applies",
        docs=(DPIA, TM),
        note="Data and asset inventories; device registry; SBOM.",
        owner="GRC",
    ),
    it(
        "ID.RA",
        "Risk Assessment",
        "applies",
        docs=(TM, RR),
        note="76 threats scored for likelihood, safety and security impact.",
        owner="SEC",
    ),
    it(
        "ID.IM",
        "Improvement",
        "partly",
        ("CTL-15",),
        (),
        "Findings become registered tasks; residual risk recomputed on each control change.",
        "SEC",
    ),
    it(
        "PR.AA",
        "Identity Management, Authentication, and Access Control",
        "applies",
        ("CTL-01", "CTL-02", "CTL-03", "CTL-04", "CTL-12", "CTL-43", "CTL-46", "CTL-47"),
        (),
        "OIDC/PKCE, default-deny endpoints, OPA, workload identity, access review procedure.",
        "SEC",
    ),
    it(
        "PR.AT",
        "Awareness and Training",
        "not_applicable",
        note="No staff to train; operator guidance is UX documentation.",
    ),
    it(
        "PR.DS",
        "Data Security",
        "applies",
        ("CTL-09", "CTL-11", "CTL-15", "CTL-16", "CTL-18", "CTL-19"),
        (DPIA,),
        "Transport protection, tamper-evident audit, redaction, retention, edge privacy.",
        "SEC",
    ),
    it(
        "PR.PS",
        "Platform Security",
        "partly",
        ("CTL-13", "CTL-25", "CTL-27", "CTL-29", "CTL-31"),
        (),
        "Verified model activation, pinned and signed artefacts, hardened edge container; cluster hardening (admission, RBAC, no mounted tokens, network policy) was checked natively on the target (P11.04).",
        "DEVOPS",
    ),
    it(
        "PR.IR",
        "Technology Infrastructure Resilience",
        "partly",
        ("CTL-23", "CTL-35", "CTL-41"),
        (),
        "Safe degraded behaviour and edge buffering; outages of the gateway, Kafka, ingestion and PostgreSQL lost nothing under load and every component restart recovered (P11.05, P11.06); a tested backup exists but no schedule; single node.",
        "DEVOPS",
    ),
    it(
        "DE.CM",
        "Continuous Monitoring",
        "applies",
        ("CTL-30", "CTL-37", "CTL-42"),
        (AIOPS,),
        "Alert rules and probes tested live; runtime detection with Falco proven on the target cluster (P09.09); alerts are not routed to an operator.",
        "OPS",
    ),
    it(
        "DE.AE",
        "Adverse Event Analysis",
        "applies",
        ("CTL-38", "CTL-48"),
        (AIOPS,),
        "Alerts and detector anomalies are correlated into incidents with unverified hypotheses.",
        "OPS",
    ),
    it(
        "RS.MA",
        "Incident Management",
        "partly",
        ("CTL-38", "CTL-21"),
        (AIOPS,),
        "Incidents are opened, owned, escalated and resolved with a chained history.",
        "OPS",
        next_task="P13.04",
    ),
    it(
        "RS.AN",
        "Incident Analysis",
        "partly",
        ("CTL-15", "CTL-48"),
        (AIOPS,),
        "Causal hypotheses are recorded and never asserted as fact; no forensic tooling.",
        "OPS",
        accepted="Out of scope for a prototype.",
    ),
    it(
        "RS.CO",
        "Incident Response Reporting and Communication",
        "partly",
        docs=(BREACH_RUNBOOK, DPIA),
        note="A breach procedure is written (P13.04) and its steps checked against real, independently-tested controls (Falco, audit export, secret rotation); the sequence as a whole and the notification channel are not live-drilled.",
        owner="GRC",
    ),
    it(
        "RS.MI",
        "Incident Mitigation",
        "applies",
        ("CTL-38", "CTL-21"),
        (AIOPS,),
        "Registered, bounded, verified remediation with escalation.",
        "OPS",
    ),
    it(
        "RC.RP",
        "Incident Recovery Plan Execution",
        "partly",
        ("CTL-38", "CTL-35"),
        (),
        "Recovery is verified from alerts, not from the adapter; a database restore after the loss of its volume was rehearsed on the target (P11.05).",
        "OPS",
    ),
    it(
        "RC.CO",
        "Incident Recovery Communication",
        "not_applicable",
        note="No stakeholders to notify in a prototype.",
    ),
]

# ----------------------------------------------------------------------------------------- ETSI EN 303 645 (as a device profile)
ETSI = [
    it(
        "5.1",
        "No universal default passwords",
        "applies",
        ("CTL-09", "CTL-14", "CTL-39"),
        (),
        "Devices authenticate with per-device certificates, never a shared password.",
        "SEC",
    ),
    it(
        "5.2",
        "Implement a means to manage reports of vulnerabilities",
        "partly",
        docs=(GIT,),
        note="Findings become registered tasks; no public disclosure policy.",
        accepted="No product is published.",
    ),
    it(
        "5.3",
        "Keep software updated",
        "partly",
        ("CTL-25", "CTL-29"),
        (),
        "Verify-then-commit model activation with rollback; signed artefacts; a rollout and a rollback of a bad image were tested on the target (P11.05); no over-the-air device update service.",
        "EDGE",
    ),
    it(
        "5.4",
        "Securely store sensitive security parameters",
        "partly",
        ("CTL-14",),
        (),
        "Secrets kept out of Git and rotated; no hardware secure element.",
        "SEC",
        accepted="Simulated devices.",
    ),
    it(
        "5.5",
        "Communicate securely",
        "applies",
        ("CTL-09", "CTL-11"),
        (),
        "Per-device mTLS with default-deny topic ACLs; TLS to the database.",
        "SEC",
    ),
    it(
        "5.6",
        "Minimize exposed attack surfaces",
        "applies",
        ("CTL-31", "CTL-09"),
        (),
        "Non-root, read-only, capability-dropped edge container; only the health port is exposed.",
        "EDGE",
    ),
    it(
        "5.7",
        "Ensure software integrity",
        "applies",
        ("CTL-25", "CTL-29"),
        (),
        "Model hash verified at load; signed artefacts.",
        "EDGE",
    ),
    it(
        "5.8",
        "Ensure that personal data is secure",
        "applies",
        ("CTL-19", "CTL-16"),
        (DPIA,),
        "Privacy zones, ephemeral identities, k-anonymity floor, redaction.",
        "GRC",
    ),
    it(
        "5.9",
        "Make systems resilient to outages",
        "applies",
        ("CTL-41", "CTL-23", "CTL-38"),
        (),
        "Durable ordered edge outbox, safe offline behaviour, verified remediation.",
        "EDGE",
    ),
    it(
        "5.10",
        "Examine system telemetry data",
        "applies",
        ("CTL-37", "CTL-42"),
        (SLOS,),
        "Bounded low-cardinality telemetry, alerts and a detector on it.",
        "OPS",
    ),
    it(
        "5.11",
        "Make it easy for users to delete user data",
        "partly",
        ("CTL-18",),
        (DPIA,),
        "Retention deletes by class; no data-subject deletion workflow is exercised.",
        "GRC",
        accepted="No consumer users.",
    ),
    it(
        "5.12",
        "Make installation and maintenance of devices easy",
        "partly",
        docs=("docs/environment/CLEAN_START.md",),
        note="Documented clean start; no device provisioning UX.",
        owner="DEVOPS",
        accepted="Simulated devices.",
    ),
    it(
        "5.13",
        "Validate input data",
        "applies",
        ("CTL-10", "CTL-32"),
        (),
        "Schema, identity and content validation at ingestion and API.",
        "DATA",
    ),
]

# ------------------------------------------------------------------------------------ IEC 62443 (foundational requirements)
IEC = [
    it(
        "FR 1",
        "Identification and authentication control (IAC)",
        "applies",
        ("CTL-01", "CTL-02", "CTL-09", "CTL-12"),
        (),
        "People through Keycloak, services by workload identity, devices by certificate.",
        "SEC",
    ),
    it(
        "FR 2",
        "Use control (UC)",
        "applies",
        ("CTL-03", "CTL-04", "CTL-05", "CTL-07", "CTL-34", "CTL-47"),
        (ROLES,),
        "Default-deny use control per endpoint and action class, four-eyes, single executor.",
        "SEC",
    ),
    it(
        "FR 3",
        "System integrity (SI)",
        "applies",
        ("CTL-10", "CTL-24", "CTL-25", "CTL-29", "CTL-22"),
        (),
        "Validated input, replay protection, model and artefact integrity.",
        "SEC",
    ),
    it(
        "FR 4",
        "Data confidentiality (DC)",
        "partly",
        ("CTL-11", "CTL-16", "CTL-17", "CTL-19"),
        (),
        "Redaction and role-limited evidence; the broker and the database links are TLS, transport between the other platform services is plain.",
        "SEC",
    ),
    it(
        "FR 5",
        "Restricted data flow (RDF)",
        "partly",
        ("CTL-13", "CTL-08", "CTL-09"),
        (ARCH,),
        "Zones and conduits are designed (TZ0-TZ8); enforcement in the cluster was tested natively (P11.04).",
        "SEC",
    ),
    it(
        "FR 6",
        "Timely response to events (TRE)",
        "applies",
        ("CTL-15", "CTL-37", "CTL-38", "CTL-42"),
        (AIOPS,),
        "Audit trail, alerts, incident correlation, remediation within 30 s of an incident (measured in P10.09).",
        "OPS",
    ),
    it(
        "FR 7",
        "Resource availability (RA)",
        "partly",
        ("CTL-23", "CTL-35", "CTL-41"),
        (BUDGET,),
        "Degraded-mode behaviour and rate limits; load, outage and a 30-minute soak measured on one node (P11.06); no redundancy.",
        "OPS",
    ),
]

# -------------------------------------------------------------------------------------- OWASP ASVS 4.0.3 chapters, API Top 10
ASVS = [
    it(
        "V1",
        "Architecture, Design and Threat Modeling",
        "applies",
        ("CTL-03", "CTL-04"),
        (TM, ARCH),
        "Threat model, trust zones and default-deny architecture.",
        "ARCH",
    ),
    it(
        "V2",
        "Authentication",
        "applies",
        ("CTL-01", "CTL-02", "CTL-43"),
        (),
        "OIDC authorization code with PKCE, lockout, refresh rotation.",
        "SEC",
    ),
    it(
        "V3",
        "Session Management",
        "applies",
        ("CTL-43", "CTL-02"),
        (),
        "Short-lived tokens held in memory; no cookie session.",
        "SEC",
    ),
    it(
        "V4",
        "Access Control",
        "applies",
        ("CTL-03", "CTL-04", "CTL-05", "CTL-17", "CTL-47"),
        (),
        "Default-deny per endpoint and per action, role-limited evidence.",
        "SEC",
    ),
    it(
        "V5",
        "Validation, Sanitization and Encoding",
        "applies",
        ("CTL-32", "CTL-10"),
        (),
        "Closed request schemas, validated cursors and ranges, escaped search.",
        "BACKEND",
    ),
    it(
        "V6",
        "Stored Cryptography",
        "partly",
        ("CTL-14", "CTL-29"),
        (),
        "Secrets rotation and signing; an encrypted backup (P11.05); no data-at-rest encryption of the database volume.",
        "SEC",
    ),
    it(
        "V7",
        "Error Handling and Logging",
        "applies",
        ("CTL-15", "CTL-16"),
        (),
        "Redacted logs and error responses, append-only audit.",
        "SEC",
    ),
    it(
        "V8",
        "Data Protection",
        "applies",
        ("CTL-16", "CTL-18", "CTL-19"),
        (DPIA,),
        "Redaction, retention, edge minimisation.",
        "GRC",
    ),
    it(
        "V9",
        "Communication",
        "partly",
        ("CTL-11", "CTL-09"),
        (),
        "TLS to the database and device mTLS, proven on the target (P11.04); internal links partly plain.",
        "SEC",
    ),
    it(
        "V10",
        "Malicious Code",
        "partly",
        ("CTL-28", "CTL-29"),
        (),
        "Scanning, SBOM and signing; no dedicated code-integrity review.",
        "DEVOPS",
        accepted="Single developer.",
    ),
    it(
        "V11",
        "Business Logic",
        "applies",
        ("CTL-05", "CTL-06", "CTL-20", "CTL-24", "CTL-22"),
        (),
        "Four-eyes, execution-time policy, safety bounds, idempotency and replay protection.",
        "CONTROL",
    ),
    it(
        "V12",
        "Files and Resources",
        "partly",
        ("CTL-32",),
        (),
        "No file upload is offered; evidence exports are redacted.",
        "BACKEND",
        accepted="No upload surface exists.",
    ),
    it(
        "V13",
        "API and Web Service",
        "applies",
        ("CTL-01", "CTL-03", "CTL-32", "CTL-33"),
        (),
        "Versioned APIs, closed schemas, rate and size limits.",
        "BACKEND",
    ),
    it(
        "V14",
        "Configuration",
        "applies",
        ("CTL-27", "CTL-33", "CTL-37"),
        (),
        "Pinned images, security headers, strict CORS, configuration drift alerts.",
        "DEVOPS",
    ),
]
OWASP_API = [
    it(
        "API1",
        "Broken Object Level Authorization (2023)",
        "applies",
        ("CTL-03", "CTL-04", "CTL-17", "CTL-47"),
        (),
        "Policy decides per route and role; evidence access is role-limited; agency scope on emergency records is P09.06's planned control.",
        "SEC",
    ),
    it(
        "API2",
        "Broken Authentication (2023)",
        "applies",
        ("CTL-01", "CTL-02", "CTL-43"),
        (),
        "Strict token validation; PKCE only.",
        "SEC",
    ),
    it(
        "API3",
        "Broken Object Property Level Authorization (2023)",
        "applies",
        ("CTL-16", "CTL-32", "CTL-17"),
        (),
        "Closed response schemas and redaction.",
        "BACKEND",
    ),
    it(
        "API4",
        "Unrestricted Resource Consumption (2023)",
        "applies",
        ("CTL-33",),
        (),
        "Rate limits, request-size limits.",
        "BACKEND",
    ),
    it(
        "API5",
        "Broken Function Level Authorization (2023)",
        "applies",
        ("CTL-03", "CTL-04", "CTL-05"),
        (),
        "Default-deny per endpoint; action class gates.",
        "SEC",
    ),
    it(
        "API6",
        "Unrestricted Access to Sensitive Business Flows (2023)",
        "applies",
        ("CTL-05", "CTL-06", "CTL-24", "CTL-34"),
        (),
        "Four-eyes, expiry, idempotency, audited override.",
        "CONTROL",
    ),
    it(
        "API7",
        "Server Side Request Forgery (2023)",
        "applies",
        ("CTL-32",),
        (),
        "The API makes no user-directed outbound requests.",
        "BACKEND",
    ),
    it(
        "API8",
        "Security Misconfiguration (2023)",
        "applies",
        ("CTL-33", "CTL-37", "CTL-27"),
        (),
        "Headers, CORS, pinned images, drift alerts.",
        "DEVOPS",
    ),
    it(
        "API9",
        "Improper Inventory Management (2023)",
        "applies",
        ("CTL-03",),
        (),
        "One endpoint inventory drives authorization and the UI; unlisted routes are denied.",
        "BACKEND",
    ),
    it(
        "API10",
        "Unsafe Consumption of APIs (2023)",
        "applies",
        ("CTL-40", "CTL-10"),
        (),
        "External integrations are simulated; inbound events are validated.",
        "BACKEND",
    ),
]

# ------------------------------------------------------------------------------------------- AI: NIST AI RMF, ISO/IEC 42001
AI_RMF = [
    it(
        "GOVERN",
        "Culture, accountability and policy for AI risk",
        "partly",
        ("CTL-05", "CTL-21"),
        (ROLES,),
        "Human authority over consequential recommendations; named control owners.",
        "LEAD",
        accepted="No organisation.",
    ),
    it(
        "MAP",
        "Context, intended use and impact of each AI system",
        "applies",
        ("CTL-26", "CTL-45"),
        (ACCEPT,),
        "Model cards state purpose and limitations; data provenance and splits are recorded.",
        "EDGE",
    ),
    it(
        "MEASURE",
        "Testing and measurement of AI risk and trustworthiness",
        "partly",
        ("CTL-25", "CTL-26", "CTL-44", "CTL-45"),
        (ACCEPT,),
        "Baselines beside every model, held-out splits with a test ledger, wide intervals reported; drift and fairness monitoring are not built.",
        "QA",
    ),
    it(
        "MANAGE",
        "Prioritised treatment and response for AI risk",
        "partly",
        ("CTL-25", "CTL-38", "CTL-44"),
        (),
        "Staged activation with rollback; a model is served only if it beats the transparent baselines; drift response is planned.",
        "OPS",
    ),
]
ISO_42001 = [
    it(
        "A.2",
        "Policies related to AI",
        "partly",
        docs=(SEC,),
        note="AI and data controls are in the baseline; no management-approved AI policy.",
        accepted="No organisation.",
    ),
    it(
        "A.3",
        "Internal organization",
        "partly",
        ("CTL-05",),
        (ROLES,),
        "Roles and authority are defined; no AI governance body.",
        "LEAD",
        accepted="No organisation.",
    ),
    it(
        "A.4",
        "Resources for AI systems",
        "applies",
        docs=(BUDGET,),
        note="Data, compute and tooling resources are recorded in the resource budget and manifests.",
        owner="ARCH",
    ),
    it(
        "A.5",
        "Assessing impacts of AI systems",
        "partly",
        ("CTL-45",),
        (DPIA, ACCEPT),
        "Safety, privacy and per-class performance are assessed; the fairness review is P12.04.",
        "GRC",
    ),
    it(
        "A.6",
        "AI system life cycle",
        "applies",
        ("CTL-25", "CTL-26"),
        (),
        "Reproducible training, model cards, verified activation and rollback.",
        "EDGE",
    ),
    it(
        "A.7",
        "Data for AI systems",
        "applies",
        ("CTL-26", "CTL-40"),
        (DPIA,),
        "Provenance, licences, split integrity, leakage checks, synthetic-versus-measured labelling.",
        "DATA",
    ),
    it(
        "A.8",
        "Information for interested parties of AI systems",
        "partly",
        docs=(ACCEPT,),
        note="Model cards and acceptance targets state measured limits; user-facing disclosure is P13.03.",
        owner="ARCH",
        next_task="P13.03",
    ),
    it(
        "A.9",
        "Use of AI systems",
        "applies",
        ("CTL-05", "CTL-21", "CTL-38"),
        (),
        "Recommendations need approval; remediation is bounded and verified.",
        "CONTROL",
    ),
    it(
        "A.10",
        "Third-party and customer relationships",
        "not_applicable",
        note="No third-party AI service or customer is involved.",
    ),
]

# ----------------------------------------------------------------------------------------- GDPR-oriented (reference only)
GDPR = [
    it(
        "Art. 5(1)(a)",
        "Lawfulness, fairness and transparency",
        "partly",
        docs=(DPIA,),
        note="Lawful-purpose assumptions are written; no legal basis is determined.",
        accepted="A legal question for qualified counsel.",
    ),
    it(
        "Art. 5(1)(b)",
        "Purpose limitation",
        "applies",
        ("CTL-19",),
        (DPIA,),
        "Each data category has a stated purpose checked against real fields.",
        "GRC",
    ),
    it(
        "Art. 5(1)(c)",
        "Data minimisation",
        "applies",
        ("CTL-19", "CTL-16"),
        (DPIA,),
        "Aggregation and privacy zones at the edge; redaction downstream.",
        "GRC",
    ),
    it(
        "Art. 5(1)(e)",
        "Storage limitation",
        "applies",
        ("CTL-18",),
        (DPIA,),
        "Retention windows enforced per class.",
        "GRC",
    ),
    it(
        "Art. 5(1)(f)",
        "Integrity and confidentiality",
        "applies",
        ("CTL-11", "CTL-15", "CTL-16", "CTL-17"),
        (),
        "Transport protection, tamper-evident audit, redaction, role-limited evidence.",
        "SEC",
    ),
    it(
        "Art. 25",
        "Data protection by design and by default",
        "applies",
        ("CTL-19", "CTL-18"),
        (DPIA,),
        "Privacy decisions are made at the edge and recorded in the inventory.",
        "GRC",
    ),
    it(
        "Art. 30",
        "Records of processing activities",
        "applies",
        docs=(DPIA,),
        note="The data inventory records categories, purposes, access, retention and rights.",
        owner="GRC",
    ),
    it(
        "Art. 32",
        "Security of processing",
        "partly",
        ("CTL-11", "CTL-14", "CTL-15", "CTL-35"),
        (),
        "Technical measures as mapped above; a tested backup exists (P11.05) but no schedule.",
        "SEC",
    ),
    it(
        "Art. 33",
        "Notification of a personal data breach",
        "partly",
        docs=(BREACH_RUNBOOK, DPIA),
        note="A breach procedure is written (P13.04), naming containment, scoping, exposure assessment and notification steps; the notification channel and timing commitment are not exercised, and no jurisdiction's legal deadline is claimed - a real deployment needs qualified counsel for that step.",
        owner="GRC",
    ),
    it(
        "Art. 35",
        "Data protection impact assessment",
        "partly",
        docs=(DPIA,),
        note="A DPIA-style review of video, trajectory and location processing is written; no supervisory-authority consultation.",
        owner="GRC",
        accepted="Not a legal DPIA.",
    ),
    it(
        "Arts. 15-22",
        "Data subject rights",
        "partly",
        docs=(DPIA,),
        note="A rights process is described per category; no workflow is exercised.",
        owner="GRC",
        accepted="No data subjects exist in a synthetic prototype.",
    ),
]

FRAMEWORKS = [
    {
        "id": "iso27001",
        "name": "ISO/IEC 27001:2022 Annex A (applicability mapping, Statement-of-Applicability style)",
        "kind": "applicability",
        "items": ISO,
    },
    {
        "id": "nist-csf-2",
        "name": "NIST Cybersecurity Framework 2.0 (categories)",
        "kind": "reference",
        "items": CSF,
    },
    {
        "id": "etsi-303645",
        "name": "ETSI EN 303 645 (consumer IoT baseline, used as a device security profile)",
        "kind": "reference",
        "items": ETSI,
    },
    {
        "id": "iec-62443",
        "name": "IEC 62443 (foundational requirements)",
        "kind": "reference",
        "items": IEC,
    },
    {"id": "owasp-asvs", "name": "OWASP ASVS 4.0.3 (chapters)", "kind": "reference", "items": ASVS},
    {
        "id": "owasp-api",
        "name": "OWASP API Security Top 10 (2023)",
        "kind": "reference",
        "items": OWASP_API,
    },
    {
        "id": "nist-ai-rmf",
        "name": "NIST AI Risk Management Framework 1.0 (functions)",
        "kind": "reference",
        "items": AI_RMF,
    },
    {
        "id": "iso-42001",
        "name": "ISO/IEC 42001:2023 Annex A (control objectives)",
        "kind": "reference",
        "items": ISO_42001,
    },
    {
        "id": "gdpr",
        "name": "GDPR (reference points only; not legal advice)",
        "kind": "reference",
        "items": GDPR,
    },
]


def build() -> dict:
    return {
        "schema_version": "1.0.0",
        "statement": STATEMENT,
        "coverage_meaning": {
            "evidenced": "every cited control is implemented and its evidence passes today",
            "partial": "at least one cited control is implemented or partial, and something is missing",
            "documented": "no control cited, but a document records the intent (intent, not enforcement)",
            "gap": "applicable, and neither a working control nor a document exists, or only planned controls do",
            "out_of_scope": "not applicable to a software prototype with no operating organisation, staff or premises",
        },
        "frameworks": FRAMEWORKS,
    }


def render(data: dict) -> str:
    return json.dumps(data, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    wanted = render(build())
    if args.check:
        current = (
            OUTPUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUTPUT.is_file() else ""
        )
        if current != wanted:
            print(f"{OUTPUT} is out of date; run security/framework_mapping.py", file=sys.stderr)
            return 1
        print("framework mapping is current")
        return 0
    OUTPUT.write_text(wanted, encoding="utf-8", newline="\n")
    print(
        f"wrote {OUTPUT} ({sum(len(f['items']) for f in FRAMEWORKS)} items in {len(FRAMEWORKS)} frameworks)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
