#!/usr/bin/env python3
"""P13.03: the API reference, generated from the real endpoint inventory and the running FastAPI app's own schema - not hand-typed, so it cannot
silently drift from what the API actually serves.

    python source-code/scripts/build_api_docs.py

Writes `docs/api/API_REFERENCE.md` and `docs/api/openapi.json`. Run `source-code/scripts/verify_api_docs.py` after any route or capability change.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

SOURCE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = SOURCE_ROOT.parent
sys.path.insert(0, str(SOURCE_ROOT))

API_DOCS = REPO_ROOT / "docs" / "api"


def load_inventory() -> dict:
    spec = importlib.util.spec_from_file_location(
        "ux_inventory", SOURCE_ROOT / "frontend" / "tools" / "inventory.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.load()


def build_openapi() -> dict:
    from backend.api.app import app  # noqa: PLC0415

    return app.openapi()


def render(inv: dict, openapi: dict) -> str:
    caps = inv["capabilities"]
    by_service: dict[str, list[dict]] = {}
    for a in inv["apis"]:
        by_service.setdefault(a.get("service", "api"), []).append(a)

    lines = [
        "# API reference",
        "",
        "Generated by `source-code/scripts/build_api_docs.py` from the real endpoint inventory (`source-code/frontend/tools/inventory.py`) and the running "
        "FastAPI app's own OpenAPI schema (`docs/api/openapi.json`) - do not hand-edit either file.",
        "",
        "Every endpoint needs a signed-in session (Keycloak, Authorization Code + PKCE) except the two named `public` below. Authorization is by **capability**, "
        "not by role directly: a request carries a role from the token, the role must hold the endpoint's capability, and the check happens on every request "
        "(`backend/api/auth.py`) - not once at sign-in. `docs/security/ROLES_AND_ACTION_AUTHORITY.md` is the fuller account of which of the 7 human roles holds "
        "which capability; the table below is generated from the same source of truth.",
        "",
        "A **write** endpoint that changes a protected resource (a command, an incident transition, an override) still goes through the policy engine a second "
        "time on its own terms - holding the capability lets you ask, it does not by itself mean the policy engine will say yes (see `diagrams/sources/"
        "04-workflow-command-safety-path.mmd`).",
        "",
        f"{len(inv['apis'])} endpoints across {len(by_service)} service(s), {len(caps)} capabilities, {len(inv['roles'])} roles. "
        f"The main API's own OpenAPI schema separately lists {len(openapi['paths'])} HTTP paths plus one WebSocket (`/api/v1/live`, not representable in OpenAPI "
        "3.0 and so listed here by hand).",
        "",
    ]

    for service in sorted(by_service):
        title = "Operator API" if service == "api" else service.replace("-", " ").title()
        lines += [f"## {title}", "", "| Method | Path | Capability | Notes |", "|---|---|---|---|"]
        for a in sorted(by_service[service], key=lambda x: x["path"]):
            cap = a.get("capability") or (
                "public, no session" if a.get("public") else "signed in only, no capability check"
            )
            note = "not in this checkout" if a.get("status") == "planned" else ""
            lines.append(f"| {a['method']} | `{a['path']}` | {cap} | {note} |")
        lines.append("")

    lines += ["## Live updates (WebSocket)", "", "| Method | Path | Capability | Notes |", "|---|---|---|---|",
               "| WS | `/api/v1/live` | same as the resources it streams | reconnects with `?since=<ISO 8601>` to replay what was missed; `backend/api/app.py` |", ""]  # fmt: skip

    lines += [
        "## Capabilities",
        "",
        "| Capability | Roles that hold it | What it covers |",
        "|---|---|---|",
    ]
    for name in sorted(caps):
        c = caps[name]
        lines.append(f"| `{name}` | {', '.join(c['roles'])} | {c['description']} |")
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    inv = load_inventory()
    openapi = build_openapi()
    API_DOCS.mkdir(parents=True, exist_ok=True)
    (API_DOCS / "API_REFERENCE.md").write_text(render(inv, openapi), encoding="utf-8", newline="\n")
    (API_DOCS / "openapi.json").write_text(
        json.dumps(openapi, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"wrote {API_DOCS / 'API_REFERENCE.md'} and {API_DOCS / 'openapi.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
