"""The defect and finding register of Phase 12 (P12.05): what was found, what was fixed and retested, and what is still open, with its impact and its owner.

A FIXED entry names the evidence that was regenerated after the fix and must still pass; an OPEN entry says what it stops the platform from doing, who owns closing it, and what the next action is;
an ACCEPTED entry is a limit the project chooses to live with, said in one sentence, and is not a claim that the limit is acceptable to the assessor (nothing here is an assessor approval).
Severities: SAFETY (a protected action or a safety property is affected), HIGH (a stated target is not met or a capability the acceptance names is missing), MEDIUM, LOW.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from acceptance.matrix import Cite as C


@dataclass(frozen=True)
class Defect:
    id: str
    title: str
    severity: str
    found_by: str
    status: str  # FIXED | OPEN | ACCEPTED
    impact: str
    owner: str
    fix: str = ""  # FIXED: what changed
    retest: tuple[C, ...] = ()  # FIXED: evidence regenerated after the fix
    next_action: str = ""  # OPEN
    reproduce: str = ""
    links: tuple[str, ...] = ()
    rows: tuple[str, ...] = field(default=())  # the matrix rows and acceptance targets it explains


DEFECTS: tuple[Defect, ...] = (
    # ================================================================== FIXED
    Defect(
        "D-02",
        "A protected action on a cross street needed no current evidence",
        "SAFETY",
        "P12.02 SAFE-03 lab: the evidence rule counted a segment with no corridor as fresh, with or without any reading",
        "FIXED",
        "one of eight cross-street segments could be the target of a diversion or a sign message with nothing current behind it: SAFE-02 ('lacking current evidence, denied') did not hold for them",
        "BACKEND/CONTROL",
        "`policy._evidence_fresh` now requires recent telemetry from the junctions at the segment's two ends; a unit test asserts the query and the refusal",
        (
            C("p12_02_safe03_stale_state", "policy_evidence_for_a_cross_street_segment"),
            C("p12_02_safe02_protected_actions", "safe_02_every_attempt_that_lacked_evidence"),
            C(
                "pytest:tests/test_evidence_freshness.py",
                "test_a_cross_street_target_with_no_recent_telemetry_is_not_fresh",
            ),
        ),
        reproduce="python source-code/acceptance/lab_stale_state.py",
        links=("SAFE-02", "SAFE-03"),
    ),
    Defect(
        "D-03",
        "A command left `executing` by a killed executor stayed `executing` for ever",
        "SAFETY",
        "P12.02 REC-02 lab: the executor was killed mid-run; nothing reconciled the command and the executor carried on to the next one",
        "FIXED",
        "after any executor crash a command could sit `executing` indefinitely, with no way out in the state machine and no signal to an operator that its outcome was unknown",
        "BACKEND/CONTROL",
        "`executor_worker.reconcile`: at start every command still `executing` is failed (not retried, saying the outcome is unknown); while running, one older than the adapter's time limit is",
        (
            C("p12_02_rec02_executor_restart", "on_start_the_new_executor_reconciles_the_orphan"),
            C(
                "p12_02_rec02_executor_restart",
                "the_orphan_was_reconciled_before_the_next_command_was_executed",
            ),
            C(
                "pytest:tests/test_executor_reconcile.py",
                "test_an_orphan_is_failed_with_the_outcome_said_to_be_unknown",
            ),
        ),
        reproduce="python source-code/acceptance/lab_executor_restart.py",
        links=("REC-02",),
    ),
    Defect(
        "D-04",
        "Ingestion sustained about 15 events per second and lost events under load",
        "HIGH",
        "P11.06 load on the target: per-event schema validation 8.8 ms, and a commit, a flush and an fsync per event",
        "FIXED",
        "the platform could not keep up with ten times the nominal load, and at nominal the p95 was 34 to 45 s",
        "BACKEND/DATA",
        "a validator built once (0.13 ms), batched ingestion commits (offsets still move only after the database commit), batched gateway outbox and Kafka flushes",
        (
            C("p11_06_target_load", "nominal_load_16_events_per_second"),
            C("p11_06_target_load", "peak_load_ten_times_nominal_loses_nothing"),
            C("pytest:tests/test_ingest_batching.py", "test_"),
        ),
        reproduce="the runbook's target load run (docs/runbooks/TARGET_DEPLOYMENT_RUNBOOK.md, verify_load_target.py)",
        links=("LOAD-01", "LOAD-02"),
    ),
    Defect(
        "D-05",
        "The MQTT gateway lost broker-acknowledged events across its own restart",
        "SAFETY",
        "P11.06 gateway outage on the target: 2,008 of 3,600 events lost; mosquitto 2.0.18 keeps no offline queue with `per_listener_settings true`",
        "FIXED",
        "events a device had been told the broker accepted were lost while the gateway restarted",
        "DEVOPS/DATA",
        "the cluster's broker has one listener and does not set the option; the gateway holds a persistent session and acknowledges after its durable outbox; a test asserts the configuration. The two-listener compose fixture keeps the loss (F-19); the application-level acknowledgement covers it end to end (REC-01 lab)",
        (
            C("p11_06_target_load", "with_gateway_taken_away_for_25_s"),
            C("p11_06_target_load", "no_event_the_broker_acknowledged_is_lost"),
            C(
                "p12_02_rec01_edge_outage",
                "every_durably_buffered_reading_reached_the_database_none_missing",
            ),
        ),
        reproduce="the target load run with the gateway outage",
        links=("LOAD-02", "REC-01"),
    ),
    Defect(
        "D-06",
        "A failed check Job was retried, hiding which run failed",
        "MEDIUM",
        "P11.06: a load that lost events was retried and the database held two runs under one label",
        "FIXED",
        "a check could turn a real loss into a pass",
        "DEVOPS",
        "`backoffLimit: 0` for every Job but the migration; a test asserts it",
        (
            C(
                "pytest:tests/test_k8s_workloads.py",
                "test_a_failed_check_job_is_not_retried_but_the_migration_is",
            ),
        ),
        links=("LOAD-03",),
    ),
    Defect(
        "D-07",
        "The load check died when PostgreSQL was taken away",
        "MEDIUM",
        "P11.06 degraded run",
        "FIXED",
        "the outage of the database could not be measured",
        "QA",
        "the checker reconnects until its own drain deadline",
        (C("p11_06_target_load", "with_postgres_taken_away_for_25_s"),),
        links=("LOAD-03",),
    ),
    Defect(
        "D-08",
        "Tempo was OOM-killed compacting hours of traces",
        "MEDIUM",
        "P11.06 rehearsal on the target: a crash loop after a few hours of load",
        "FIXED",
        "traces stopped being stored on the target",
        "DEVOPS",
        "768 MiB limit; the runbook says to delete a crash-looping StatefulSet pod after a limit change",
        (
            C(
                "p11_03_target_deployment",
                "prometheus_scrapes_the_edge_runtime_and_tempo_and_both_are_up",
            ),
        ),
        links=("RQ18",),
    ),
    Defect(
        "D-09",
        "Restart times were measured with `rollout status`, which answers at once for a deleted pod",
        "MEDIUM",
        "P11.05 rehearsal: 'ready in 0.1 s'",
        "FIXED",
        "the recovery times reported were wrong",
        "QA",
        "a restart is timed to the first NEW pod that is Ready",
        (C("p11_05_target_recovery", "after_a_restart_of_", 8),),
        links=("REC-02",),
    ),
    Defect(
        "D-10",
        "The runbook drill misread a command that prints its answer last, and overwrote its own evidence",
        "LOW",
        "P11.08 drill",
        "FIXED",
        "a correct step looked failed; earlier evidence was lost",
        "DEVOPS",
        "one output stream in order; one evidence file per set of phases",
        (C("p11_08_runbook_drill_deploy", "runbook_step_remove-previous"),),
        links=("RQ22",),
    ),
    Defect(
        "D-11",
        "Falco alerts named the user as `<NA>` and the check accepted it as a name",
        "MEDIUM",
        "P09.09 on the target",
        "FIXED",
        "an alert did not identify who ran the action",
        "SEC",
        "the rules add the numeric uid and the check requires it",
        (C("p09_09_falco_target", "numeric_uid"),),
        links=("RQ19",),
    ),
    Defect(
        "D-12",
        "Verifiers polluted each other through the one shared verification database",
        "MEDIUM",
        "P12.01 run: a leftover collision closed a segment for the routing check, leftover KPI windows changed the KPI counts, an unexecuted command was taken by the next executor",
        "FIXED",
        "a verifier could fail or pass because of another one; results depended on order",
        "QA",
        "`run_catalog.py` quiets the database between runs (every live incident resolved, every waiting command expired through the repository)",
        (
            C(
                "p07_02_routing",
                "the_router_never_uses_a_closed_segment_and_the_grid_still_finds_a_way_through",
            ),
            C("p05_08_repositories", "concurrent_transitions_serialize_exactly_one_wins"),
        ),
        links=("RQ22",),
    ),
    Defect(
        "D-13",
        "Five verifiers had drifted from the platform they verify",
        "MEDIUM",
        "P12.01 run: the repositories check assumed a retired lifecycle (approved to denied illegal; two different transitions racing), the routing check missed a field the console needs, the observability check's message double lacked what the gateway now reads, the observability-stack check needed a docker CLI, the KPI check assumed an empty table",
        "FIXED",
        "green evidence from the past was not evidence about the present",
        "QA",
        "each verifier corrected to the current, documented behaviour and re-run",
        (
            C(
                "p05_08_repositories",
                "command_invalid_transition_from_approved_straight_to_executed_rejected",
            ),
            C("p07_02_routing", "api_serves_contract_shaped_route_alternatives"),
            C("p10_01_observability", "."),
            C("p10_03_observability_stack", "."),
            C("p06_01_kpis", "recompute_is_idempotent_no_duplicate_rows"),
        ),
        links=("RQ22",),
    ),
    Defect(
        "D-14",
        "The manifest verifier rejected workload names with digits",
        "LOW",
        "P09.10 re-run after the target work added the `aiops-e2e` Job",
        "FIXED",
        "a regression check failed on a valid name",
        "SEC",
        "the pattern accepts digits",
        (
            C(
                "p09_04_workload_protection",
                "the_kubernetes_rbac_and_networkpolicy_manifests_are_structurally_valid_and_internally_consistent",
            ),
        ),
        links=("RQ19",),
    ),
    Defect(
        "D-15",
        "The API image lacked a file it reads at start",
        "HIGH",
        "P11.03 deployment on the target",
        "FIXED",
        "every API request was a 5xx in the cluster",
        "DEVOPS",
        "the file is in the image and the image build starts the API as a smoke test",
        (
            C(
                "p11_01_service_images",
                "backend_every_module_the_service_scripts_import_imports_and_the_operator_api_answers_its_health_check",
            ),
        ),
        links=("RQ15",),
    ),
    Defect(
        "D-16",
        "The database image accepted a plain (non-TLS) connection",
        "HIGH",
        "P11.03 on the target",
        "FIXED",
        "the cluster's database did not enforce TLS",
        "SEC",
        "`pg_hba.conf` is `hostssl` only",
        (C("p11_04_target_security", "postgres_refuses_a_connection_that_is_not_tls"),),
        links=("CTL-11",),
    ),
    Defect(
        "D-17",
        "The new-command dialog could be submitted before its list of targets had loaded",
        "LOW",
        "P12.01 UI sweep (P08.08 spec): the request went out with an empty target and the person was shown the API's validation text",
        "FIXED",
        "nothing was executed or wrongly requested, but a person who was quick saw an API field error instead of being told to wait",
        "FRONTEND",
        "the dialog refuses to submit with no target chosen and says whether the list is still loading; the spec waits for the target to appear before it types",
        (C("p08_08_ui_actions", "a person who requested a command sees they cannot decide it"),),
    ),
    Defect(
        "D-18",
        "The console's demo data relied on a failure the platform no longer lets happen",
        "LOW",
        "P12.01 UI sweep: the seeded `failed` command targeted a segment that exists nowhere and expected the adapter to fail it; since the executor's policy gate (P09.03) that command is denied before the adapter is driven",
        "FIXED",
        "the console's failed-command screens were not being exercised with a real failure; the acceptance run reported the P08.08 spec as failing",
        "FRONTEND/QA",
        "the seed now leaves a command `executing` as if its executor had died, and the running executor fails it (REC-02, D-03) with the outcome said to be unknown; the UI runner also waits for the demo database to be rebuilt instead of a fixed 45 s, after one run seeded before a slow reset wiped the data",
        (
            C(
                "p08_08_ui_actions",
                "the list shows every lifecycle state as its own shape and word",
            ),
            C(
                "p08_08_ui_actions",
                "failed, expired and policy-unavailable commands each say what happened",
            ),
        ),
    ),
    Defect(
        "D-19",
        "The data inventory declared the wrong retention class for edge-camera aggregate metadata, and had gone stale about whether any such device is registered",
        "LOW",
        "P12.02 runtime-acceptance re-run (P09.06 data inventory): a live `(edge_camera, aggregated, short)` combination was not covered by any category",
        "FIXED",
        "the document said `standard` (90 days) while `edge/vision_devices.py` has always registered these devices with `retention_class: short` (7 days); the document also still claimed 0 such devices were registered, which stopped being true once P06.06's own verifier (`verify_vru_conflicts.py`) began registering its illustrative cameras against the shared verification database",
        "GRC",
        "`security/data_inventory.json`'s `edge-vision-aggregate-metadata` category now declares `short`, matching the code, and its note names the real source of any live instances instead of claiming there are none",
        (
            C(
                "p09_06_data_inventory",
                "every_live_device_type_privacy_retention_combination_in_either_database_is_covered_by_a_category",
            ),
            C(
                "p09_06_data_inventory",
                "the_generated_tables_in_the_data_inventory_document_are_current",
            ),
        ),
        reproduce="python source-code/security/verify_data_inventory.py --render",
    ),
    # ================================================================== OPEN
    Defect(
        "D-01",
        "The signal-failure scenario has no implementation: no detection, no safe plan, no maintenance work",
        "HIGH",
        "P12.01 matrix, scenario 5: a controller-reported fault is deliberately not a safety candidate and nothing else raises it; there is no safe-plan action and no maintenance work item",
        "OPEN",
        "acceptance scenario 5 of the project plan cannot be demonstrated; on a controller failure the platform can only refuse to act, it cannot put the junction on a safe plan or tell a crew",
        "OPS/CONTROL",
        next_action="a detector over `signal.controller.spat` (a reported fault, an invalid phase, a stuck phase), an incident of the existing `signal_fault` type, a governed safe-plan action through the same request, approval and verification path, and a maintenance work item; then rows S5.1-S5.4 and Q-S7 are re-run",
        links=("RQ25",),
        rows=("S5.1", "S5.2", "S5.3", "S5.4", "Q-S7"),
    ),
    Defect(
        "F-02",
        "The trained 30-minute density forecast is significantly worse than the baseline on the held-out test",
        "MEDIUM",
        "P06.08 and the P12.03 re-read of ACC-02",
        "OPEN",
        "the platform serves the baseline for that target, labelled so: predictions are weak but honest",
        "DATA/OPS",
        next_action="more data or a better model; until then the baseline is served and the row says so",
        links=("ACC-02",),
        rows=("S1.2",),
    ),
    Defect(
        "F-03",
        "Flooding is detected from a sensor flag and friction only; rainfall, water depth, the loop-detector speed drop and reports are not combined",
        "MEDIUM",
        "P12.01 matrix, scenario 4",
        "OPEN",
        "the scenario's 'combine rainfall, water depth, speed reduction and reports' is not met: a flood is found from the road-condition sensor's flag and friction alone (a flooding incident on a corridor does get a diversion that avoids the whole corridor - P12.05 check, `p07_04_recommendations`)",
        "DATA",
        next_action="a fusion rule over the weather and road-condition sensors and the loop speeds",
        links=("RQ25",),
        rows=("S4.1",),
    ),
    Defect(
        "F-04",
        "Outcomes by corridor cannot be compared: the held-out runs hold too few truth episodes",
        "LOW",
        "P12.04 by-place analysis: corridor C has 3, A 15 and B 8; the frozen detector's recall is 0.27, 0.25 and 0.67 with overlapping intervals",
        "OPEN",
        "no disparity is shown and none is excluded",
        "DATA",
        next_action="more held-out runs per corridor (a new split, not a reopened one)",
        links=("ACC-03",),
        rows=("Q-F1",),
    ),
    Defect(
        "F-05",
        "Emergency calls are not an input to incident correlation",
        "MEDIUM",
        "P12.01 matrix, scenario 2",
        "OPEN",
        "a person links a call to an incident; the platform does not fuse call evidence with sensor evidence",
        "ARCH/EMERG",
        next_action="a call-derived candidate with its own modality in the correlator, with the privacy limits of the call record",
        links=("RQ25",),
        rows=("S2.2",),
    ),
    Defect(
        "F-06",
        "The variable-message-sign adapter records a message but nothing is actuated, and no public-alert channel exists",
        "LOW",
        "P07.06 and P12.01 scenarios 2 and 4",
        "ACCEPTED",
        "'the warning was published' is a recorded command, not an observed change on the road; no public alerting is authorized",
        "CONTROL",
        links=("RQ25",),
        rows=("S2.5", "S4.3"),
    ),
    Defect(
        "F-07",
        "The cyclist conflict mode is unvalidated",
        "MEDIUM",
        "P06.06: the simulator has no real cyclist conflict",
        "OPEN",
        "nothing can be said about outcomes for cyclists",
        "SIM/DATA",
        next_action="a cyclist-conflict scenario in the simulator with truth, then the same evaluation as for pedestrians",
        links=("RQ25",),
        rows=("Q-F6",),
    ),
    Defect(
        "F-08",
        "AIOps platform-incident false positives are 29.6% against a 10% target (FA-03)",
        "HIGH",
        "P10.09 incident quality on 28 held-out runs",
        "OPEN",
        "the served detector plus correlator raises incidents that are not real more often than the target allows",
        "OPS",
        next_action="tune the correlator's grouping and hysteresis on validation, then one non-selecting test opening",
        links=("FA-03",),
    ),
    Defect(
        "F-09",
        "The operational anomaly detector did not transfer to lab traffic and its test false-alarm rate is above budget",
        "MEDIUM",
        "P10.06",
        "OPEN",
        "the model is reported, not served as the primary detector",
        "OPS/DATA",
        next_action="collect lab-traffic training runs; keep the robust z-score baseline until then",
        links=("ACC-04",),
    ),
    Defect(
        "F-10",
        "Eleven security controls are partial with a stated gap and fourteen lack a positive or a negative runtime check",
        "MEDIUM",
        "P09.10 coverage reading",
        "OPEN",
        "the residual risk of those controls is computed as not reduced",
        "SEC",
        next_action="each gap is in `security/controls.json` with its owner and due date; close or accept them one by one",
        links=("RQ20",),
    ),
    Defect(
        "F-11",
        "No scheduled backup, no off-host copy, the key sits beside the archive, Keycloak's embedded database is not backed up",
        "MEDIUM",
        "P11.05",
        "OPEN",
        "the recovery point in real use is however long ago an operator last ran a backup",
        "DEVOPS",
        next_action="a schedule, an off-host copy, custody of the key, and a supported Keycloak database",
        links=("REC-03",),
    ),
    Defect(
        "F-12",
        "Service-to-service traffic inside the namespace is plain and unauthenticated (confined by NetworkPolicy only)",
        "MEDIUM",
        "P11.04: CTL-11 stays partial",
        "OPEN",
        "a compromised workload in the namespace could talk to Kafka, the policy engine and Keycloak on the paths the policy allows",
        "SEC",
        next_action="per-service certificates or a mesh",
        links=("RQ19",),
    ),
    Defect(
        "F-13",
        "Falco alerts are not routed to an operator",
        "LOW",
        "P09.09: CTL-30 stays partial",
        "OPEN",
        "a runtime detection is written to Falco's own log and nowhere an operator would see it",
        "OPS/SEC",
        next_action="Falco to the alerting stack (Loki, Alertmanager)",
        links=("RQ19",),
    ),
    Defect(
        "F-14",
        "Scale, failover and quarantine remediation are plan-only",
        "LOW",
        "P10.08",
        "ACCEPTED",
        "remediation covers restart, model rollback and a sampling override; the other actions are documented, not built",
        "OPS",
        links=("RQ07",),
    ),
    Defect(
        "F-15",
        "No screen-reader session and no assistive-technology user has used the console",
        "MEDIUM",
        "P12.04 accessibility rows",
        "OPEN",
        "what automated checks cannot see is untested",
        "UX/PRESENT",
        next_action="a session with a real person",
        links=("UX-01",),
        rows=("Q-A7",),
    ),
    Defect(
        "F-16",
        "Demographic and vulnerable-group outcomes cannot be measured: the district holds no population data",
        "LOW",
        "P12.04 fairness rows",
        "ACCEPTED",
        "no claim about people is possible and none is made",
        "GRC",
        links=("RQ20",),
        rows=("Q-F7",),
    ),
    Defect(
        "F-17",
        "No remote cloud execution: the central tier runs locally and on one real host",
        "HIGH",
        "RQ03 in the traceability matrix",
        "OPEN",
        "whether a locally deployed central tier plus a proposed cloud architecture (ADR-0007) satisfies the assessment is the assessor's decision",
        "ARCH/LEAD",
        next_action="ask the assessor; if a remote tier is required, deploy the same manifests to it",
        links=("RQ03",),
    ),
    Defect(
        "F-18",
        "A hard crash of the MQTT broker inside its 5-second persistence interval could drop acknowledged events; not injected",
        "MEDIUM",
        "P11.06 limit",
        "OPEN",
        "the device's own outbox and the application acknowledgement are the guarantee and are proven (REC-01), but the broker-side loss window was not measured",
        "DEVOPS/QA",
        next_action="kill the broker container hard during a load and count",
        links=("LOAD-02",),
    ),
    Defect(
        "F-19",
        "The two-listener compose fixture keeps `per_listener_settings true` and so keeps no offline queue for the gateway",
        "LOW",
        "P11.06",
        "ACCEPTED",
        "development only: the fixture needs an anonymous and an authenticated listener side by side; its file says so",
        "DEVOPS",
        links=("LOAD-02",),
    ),
    Defect(
        "F-20",
        "The hosted CI run has not happened (P01.05)",
        "LOW",
        "needs a push, which is the user's",
        "OPEN",
        "the workflow's behaviour on a hosted runner is untested",
        "DEVOPS",
        next_action="after the user's push",
        links=("RQ14",),
    ),
)
