"""Every verifier the platform has, in the order it is safe to run them against one shared live stack (P12.01, P12.06).

The order follows the dependencies of the tasks (the database and the messaging first, the workflows that build on them next, the two long AIOps labs last) because the verifiers share one
database: an incident or a command left behind by one can change what the next sees, so they run one at a time. `groups` lets a caller run a slice.

`argv` is relative to `source-code/`; `cwd` defaults to it. A run passes when its process exits 0; the evidence files it changed are read afterwards and any failing check is listed.
`target` runs are the Phase 11 runs on the real host: they are listed (so the evidence index is complete) but not run from here - their commands are in the runbook and the host was cleaned afterwards.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Run:
    id: str
    task: str
    title: str
    argv: tuple[str, ...]
    group: str
    minutes: int
    needs: tuple[str, ...] = ()
    cwd: str = "."
    evidence: tuple[
        str, ...
    ] = ()  # docs/evidence names the run is expected to write (checked after it ran)


# Most verifiers write `infra/platform/output/<task>_evidence.json`; the register links the copy in `docs/evidence/<name>.json`, which the runner refreshes. These are the
# ones whose output file is not named after the run's task.
OUTPUT_OF = {
    "p05_09_scenario_control": "p05_09_evidence.json",
    "p08_09_demo_controls": "p08_09_demo_controls_evidence.json",
    "p08_04_auth_api": "p08_04_evidence.json",
    "p08_07_operator_actions_api": "p08_07_evidence.json",
    "p08_08_command_workflow_api": "p08_08_evidence.json",
    "p08_09_govern_api": "p08_09_evidence.json",
    "p09_02_keycloak": "p09_02_evidence.json",
    "p06_03_forecast_model": "p06_03_evidence.json",
    "p10_04_alert_rules": "p10_04_alerts_evidence.json",
    "p10_01_observability": "p10_01_evidence.json",
    "p10_03_observability_stack": "p10_03_evidence.json",
    "p10_02_slos": "p10_02_evidence.json",
}

RUNS: tuple[Run, ...] = (
    # ---- offline: no stack needed
    Run(
        "unit-tests",
        "P01.05",
        "Python unit tests (the whole tree)",
        ("-m", "pytest", "-q", "-p", "no:cacheprovider"),
        "offline",
        3,
    ),
    Run(
        "simulator-bounds",
        "P03.09",
        "Cross-stage invariants over the generated simulator output",
        ("simulator/verification/verify_bounds.py",),
        "offline",
        1,
        evidence=("bounds_report",),
    ),
    Run(
        "ux-wireframes",
        "P08.02",
        "Wireframes complete, consistent and rendered",
        ("frontend/tools/verify_wireframes.py",),
        "offline",
        3,
        evidence=("p08_02_wireframes",),
    ),
    Run(
        "ux-inventory",
        "P08.01",
        "UX inventory against roles, capabilities and the served endpoints",
        ("frontend/tools/inventory.py",),
        "offline",
        1,
        evidence=("p08_01_inventory",),
    ),
    Run(
        "ux-design",
        "P08.03",
        "Design tokens, computed contrast pairs, status vocabulary",
        ("frontend/tools/design.py",),
        "offline",
        1,
        evidence=("p08_03_design",),
    ),
    Run(
        "operations-dataset",
        "P10.05",
        "Operational datasets measured, labelled, hashed, split",
        ("models/operations_dataset/verify_operations_dataset.py",),
        "offline",
        2,
        evidence=("p10_05_operations_dataset",),
    ),
    Run(
        "operations-detector",
        "P10.06",
        "Operational anomaly detector package and reproduction",
        ("models/operations_detector/verify_operations_detector.py",),
        "offline",
        3,
        evidence=("p10_06_operations_detector",),
    ),
    Run(
        "data-quality",
        "P10.10",
        "Data-quality detector package and independent reproduction",
        ("models/data_quality/verify_data_quality.py",),
        "offline",
        8,
        evidence=("p10_10_data_quality",),
    ),
    Run(
        "workloads",
        "P11.02",
        "Kubernetes workloads valid and least-privilege",
        ("infra/k8s/verify_workloads.py",),
        "offline",
        1,
        evidence=("p11_02_workloads",),
    ),
    Run(
        "adapter-claims",
        "P11.07",
        "No unearned protocol-compatibility claim",
        ("infra/verify_adapter_claims.py",),
        "offline",
        1,
        evidence=("p11_07_adapter_claims",),
    ),
    Run(
        "threat-model",
        "P09.01",
        "Threat model and control catalogue consistent with evidence",
        ("security/verify_threat_model.py",),
        "offline",
        2,
        evidence=("p09_01_threat_model",),
    ),
    Run(
        "control-mapping",
        "P09.07",
        "Framework mapping consistent with controls and register",
        ("security/verify_control_mapping.py",),
        "offline",
        2,
        evidence=("p09_07_control_mapping",),
    ),
    # ---- stack: the data path
    Run(
        "migrations",
        "P05.04",
        "Migrations apply, tamper-detect and roll forward",
        ("database/verify_migrate.py",),
        "stack",
        3,
        ("stack",),
        evidence=("p05_04_migrations",),
    ),
    Run(
        "gateway",
        "P05.03",
        "MQTT gateway: validation, outbox, backpressure across a real broker outage",
        ("backend/gateway/verify_gateway.py",),
        "stack",
        6,
        ("stack", "docker"),
        evidence=("p05_03_gateway",),
    ),
    Run(
        "ingestion",
        "P05.05",
        "Kafka to PostgreSQL ingestion: idempotence, rejection, replay",
        ("backend/ingestion/verify_ingest.py",),
        "stack",
        5,
        ("stack",),
        evidence=("p05_05_ingestion",),
    ),
    Run(
        "network-state",
        "P05.06",
        "Authoritative network state from observations",
        ("backend/state/verify_network_state.py",),
        "stack",
        3,
        ("stack",),
        evidence=("p05_06_network_state",),
    ),
    Run(
        "repositories",
        "P05.08",
        "Incident, dispatch and command repositories",
        ("backend/repositories/verify_repositories.py",),
        "stack",
        3,
        ("stack",),
        evidence=("p05_08_repositories",),
    ),
    Run(
        "retention",
        "P05.10",
        "Retention and partition policy",
        ("database/verify_retention.py",),
        "stack",
        3,
        ("stack",),
        evidence=("p05_10_retention",),
    ),
    Run(
        "api",
        "P05.07",
        "Versioned REST and WebSocket API under uvicorn",
        ("backend/api/verify_api.py",),
        "stack",
        4,
        ("stack",),
        evidence=("p05_07_api",),
    ),
    Run(
        "scenario-control",
        "P05.09",
        "Scenario control service and its separate identity",
        ("backend/scenario_control/verify_scenario_control.py",),
        "stack",
        5,
        ("stack",),
        evidence=("p05_09_scenario_control",),
    ),
    Run(
        "keycloak",
        "P09.02",
        "Keycloak realm and the authorization-code attacks",
        ("infra/platform/keycloak/verify_keycloak.py",),
        "stack",
        2,
        ("stack",),
        evidence=("p09_02_keycloak",),
    ),
    Run(
        "policy",
        "P09.03",
        "OPA authorization at the API and at the worker",
        ("policy/verify_policy.py",),
        "stack",
        4,
        ("stack",),
        evidence=("p09_03_policy",),
    ),
    Run(
        "audit-protection",
        "P09.05",
        "Audit trail, redaction and export",
        ("backend/verify_audit_protection.py",),
        "stack",
        2,
        ("stack",),
        evidence=("p09_05_audit_protection",),
    ),
    Run(
        "workload-protection",
        "P09.04",
        "Database TLS, workload identity, secret rotation",
        ("database/verify_workload_protection.py",),
        "stack",
        2,
        ("stack",),
        evidence=("p09_04_workload_protection",),
    ),
    Run(
        "data-inventory",
        "P09.06",
        "Data inventory against the live schema",
        ("security/verify_data_inventory.py",),
        "stack",
        2,
        ("stack",),
        evidence=("p09_06_data_inventory",),
    ),
    Run(
        "observability",
        "P10.01",
        "One correlation id at every hop",
        ("backend/verify_observability.py",),
        "stack",
        2,
        ("stack",),
        evidence=("p10_01_observability",),
    ),
    Run(
        "slos",
        "P10.02",
        "SLO definitions and the ingest latency measurement",
        ("backend/verify_slos.py",),
        "stack",
        2,
        ("stack",),
        evidence=("p10_02_slos",),
    ),
    Run(
        "observability-stack",
        "P10.03",
        "Prometheus, Grafana, Tempo, Loki live",
        ("infra/platform/verify_observability_stack.py",),
        "stack",
        3,
        ("stack",),
        evidence=("p10_03_observability_stack",),
    ),
    # ---- analytics: traffic intelligence
    Run(
        "kpis",
        "P06.01",
        "Corridor KPIs against simulator ground truth",
        ("backend/analytics/verify_kpis.py",),
        "analytics",
        5,
        ("stack",),
        evidence=("p06_01_kpis",),
    ),
    Run(
        "forecasts",
        "P06.03",
        "Short-horizon forecast service",
        ("backend/analytics/verify_forecasts.py",),
        "analytics",
        4,
        ("stack",),
        evidence=("p06_03_forecast_model",),
    ),
    Run(
        "congestion",
        "P06.04",
        "Congestion and spillback detection",
        ("backend/analytics/verify_congestion.py",),
        "analytics",
        4,
        ("stack",),
        evidence=("p06_04_congestion",),
    ),
    Run(
        "safety-candidates",
        "P06.05",
        "Safety candidates (blockage, stopped vehicle)",
        ("backend/analytics/verify_safety_candidates.py",),
        "analytics",
        4,
        ("stack",),
        evidence=("p06_05_safety",),
    ),
    Run(
        "vru-conflicts",
        "P06.06",
        "Pedestrian and cyclist conflict candidates",
        ("backend/analytics/verify_vru_conflicts.py",),
        "analytics",
        4,
        ("stack",),
        evidence=("p06_06_vru_conflicts",),
    ),
    Run(
        "incidents",
        "P06.07",
        "Explainable incident correlation",
        ("backend/analytics/verify_incidents.py",),
        "analytics",
        5,
        ("stack",),
        evidence=("p06_07_incidents",),
    ),
    # ---- emergency coordination and governed control (the simulator runs in the pinned SUMO container)
    Run(
        "emergency",
        "P07.01",
        "Emergency calls, units and state",
        ("backend/emergency/verify_emergency.py",),
        "emergency",
        3,
        ("stack",),
        evidence=("p07_01_emergency",),
    ),
    Run(
        "routing",
        "P07.02",
        "Live-state-aware routing with uncertainty",
        ("backend/routing/verify_routing.py",),
        "emergency",
        3,
        ("stack",),
        evidence=("p07_02_routing",),
    ),
    Run(
        "cross-agency",
        "P07.03",
        "Cross-agency coordination and CAD abstraction",
        ("backend/emergency/verify_cross_agency.py",),
        "emergency",
        3,
        ("stack",),
        evidence=("p07_03_cross_agency",),
    ),
    Run(
        "recommendations",
        "P07.04",
        "Recommendations that cannot invoke an adapter",
        ("backend/control/verify_recommendations.py",),
        "emergency",
        4,
        ("stack",),
        evidence=("p07_04_recommendations",),
    ),
    Run(
        "commands",
        "P07.05",
        "Protected commands: evidence, policy, expiry, idempotency, bounds",
        ("backend/control/verify_commands.py",),
        "emergency",
        5,
        ("stack",),
        evidence=("p07_05_commands",),
    ),
    Run(
        "simulator-adapters",
        "P07.06",
        "Control adapters against the simulator",
        ("backend/control/verify_simulator_adapters.py",),
        "emergency",
        12,
        ("stack", "docker", "sumo"),
        evidence=("p07_06_simulator_adapters",),
    ),
    Run(
        "preemption",
        "P07.07",
        "Emergency signal pre-emption with pedestrian clearance",
        ("backend/control/verify_preemption.py",),
        "emergency",
        15,
        ("stack", "docker", "sumo"),
        evidence=("p07_07_preemption",),
    ),
    Run(
        "transit-priority",
        "P07.08",
        "Transit signal priority",
        ("backend/control/verify_transit_priority.py",),
        "emergency",
        12,
        ("stack", "docker", "sumo"),
        evidence=("p07_08_transit_priority",),
    ),
    Run(
        "outcomes",
        "P07.09",
        "Independent outcome verification and rollback",
        ("backend/control/verify_outcomes.py",),
        "emergency",
        15,
        ("stack", "docker", "sumo"),
        evidence=("p07_09_outcomes",),
    ),
    Run(
        "scenarios",
        "P07.10",
        "Ambulance, fire and police scenarios end to end",
        ("backend/control/verify_scenarios.py",),
        "emergency",
        60,
        ("stack", "docker", "sumo"),
        evidence=("p07_10_scenarios",),
    ),
    # ---- the API side of the operator workflows
    Run(
        "api-auth",
        "P08.04",
        "API token enforcement matrix",
        ("backend/api/verify_auth.py",),
        "api",
        3,
        ("stack",),
        evidence=("p08_04_auth_api",),
    ),
    Run(
        "api-operator-actions",
        "P08.07",
        "Incident and dispatch actions",
        ("backend/api/verify_operator_actions.py",),
        "api",
        5,
        ("stack",),
        evidence=("p08_07_operator_actions_api",),
    ),
    Run(
        "api-command-workflow",
        "P08.08",
        "Request, approve, execute, verify",
        ("backend/api/verify_command_workflow.py",),
        "api",
        10,
        ("stack", "docker", "sumo"),
        evidence=("p08_08_command_workflow_api",),
    ),
    Run(
        "api-govern",
        "P08.09",
        "Audit, platform status, shift handover",
        ("backend/api/verify_govern.py",),
        "api",
        5,
        ("stack",),
        evidence=("p08_09_govern_api",),
    ),
    # ---- the operator console in a real browser
    Run(
        "ui",
        "P08.10",
        "Operator console, every role, in real Chrome (axe, keyboard, viewports, latency)",
        ("acceptance/run_ui.py",),
        "ui",
        60,
        ("stack", "chrome"),
        evidence=(
            "p08_04_ui_auth",
            "p08_05_ui_map",
            "p08_06_ui_analytics",
            "p08_07_ui_incident_dispatch",
            "p08_08_ui_actions",
            "p08_09_ui_govern",
            "p08_10_ui_acceptance",
        ),
    ),
    # ---- AIOps
    Run(
        "platform-incidents",
        "P10.07",
        "Platform signals correlate into incidents",
        ("backend/aiops/verify_platform_incidents.py",),
        "aiops",
        5,
        ("stack",),
        evidence=("p10_07_platform_incidents",),
    ),
    Run(
        "remediation",
        "P10.08",
        "Bounded, policy-controlled remediation",
        ("backend/aiops/verify_remediation.py",),
        "aiops",
        8,
        ("stack",),
        evidence=("p10_08_remediation",),
    ),
    Run(
        "alerts",
        "P10.04",
        "Alert rules: promtool, mutation, live faults (about 35 minutes)",
        ("backend/aiops/verify_alerts.py",),
        "aiops-lab",
        45,
        ("stack", "docker"),
        evidence=("p10_04_alert_rules",),
    ),
    Run(
        "recovery",
        "P10.09",
        "AIOps recovery on controlled faults (about 90 minutes)",
        ("backend/aiops/verify_recovery.py",),
        "aiops-lab",
        110,
        ("stack", "docker"),
        evidence=("p10_09_recovery",),
    ),
    # ---- security acceptance re-runs the security verifiers once more, so it comes after everything it reads
    Run(
        "runtime-acceptance",
        "P09.10",
        "Security controls exercised again and coverage stated",
        ("security/verify_runtime_acceptance.py",),
        "security",
        12,
        ("stack",),
        evidence=("p09_10_runtime_acceptance",),
    ),
)

# Phase 11 runs on the real host, and the runs that need another machine's tools. Listed for the evidence index; their commands are in the runbook.
TARGET_RUNS: tuple[tuple[str, str, str, tuple[str, ...]], ...] = (
    (
        "target-deploy",
        "P11.03",
        "Deployment on the real host, images checked against the signed ones",
        ("p11_03_target_deployment", "p11_08_runbook_drill_deploy"),
    ),
    (
        "target-security",
        "P11.04",
        "Native transport, identity, policy, admission, RBAC and network checks",
        ("p11_04_target_security",),
    ),
    ("target-falco", "P09.09", "Falco as a DaemonSet naming the pod", ("p09_09_falco_target",)),
    (
        "target-recovery",
        "P11.05",
        "Backup, disaster restore, restarts, rollout and rollback",
        ("p11_05_target_recovery",),
    ),
    (
        "target-load",
        "P11.06",
        "Load, ceiling, four outages and a 30-minute soak",
        ("p11_06_target_load",),
    ),
    (
        "target-runbook",
        "P11.08",
        "The runbook followed as written: reconcile, recovery, teardown",
        ("p11_08_runbook_drill_reconcile_recover", "p11_08_runbook_drill_teardown"),
    ),
    (
        "images",
        "P11.01",
        "Service images: reproducible build, scan, SBOM, signed provenance (WSL)",
        ("p11_01_service_images",),
    ),
    ("falco-rules", "P09.09", "Falco rules on the local kernel (WSL)", ("p09_09_falco_rules",)),
)
