"""P08.03: build and verify the design handoff.

    python source-code/frontend/tools/design.py --build   # tokens.css and the generated tables
    python source-code/frontend/tools/design.py           # verify everything, write evidence

Verification proves the handoff is real rather than described:
* `tokens.css` is exactly what `tokens.json` generates;
* every declared foreground/background pair meets its WCAG 2.2 minimum
  (4.5:1 text, 3:1 non-text), computed here, not asserted;
* every departure from the design system's MASTER.md is justified by a
  measurement that is re-run (the replaced value really does fail);
* every state a backend record can be in - read from the repositories and
  migrations, not retyped - has a label, a shape and a tone, and no two states
  of one domain share a shape or a label, so lifecycles are distinct in
  greyscale;
* every component section has purpose, anatomy, states, keyboard, ARIA, tokens
  and used-by; every token and screen it names exists; the screen composition
  table and the components' used-by lists agree in both directions.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

SOURCE_ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = SOURCE_ROOT.parent
sys.path.insert(0, str(SOURCE_ROOT))

from backend.evidence import Evidence  # noqa: E402
from backend.repositories import commands as cmd_repo  # noqa: E402
from backend.repositories import emergency as em_repo  # noqa: E402
from backend.repositories import incidents as inc_repo  # noqa: E402
from backend.repositories import outcomes as out_repo  # noqa: E402

DESIGN = SOURCE_ROOT / "frontend" / "src" / "design"
TOKENS, STATUS, CSS = DESIGN / "tokens.json", DESIGN / "status.json", DESIGN / "tokens.css"
INVENTORY = SOURCE_ROOT / "frontend" / "src" / "config" / "inventory.json"
DOC = REPO_ROOT / "docs" / "ux" / "DESIGN_SYSTEM.md"
MASTER = (
    REPO_ROOT
    / "design-system"
    / "intelligent-traffic-and-emergency-response-platform"
    / "MASTER.md"
)
MIGRATIONS = SOURCE_ROOT / "database" / "migrations"
BEGIN, END = "<!-- BEGIN GENERATED: design -->", "<!-- END GENERATED: design -->"
REQUIRED_FIELDS = ("Purpose", "Anatomy", "States", "Keyboard", "ARIA", "Tokens", "Used by")
CSS_GROUPS = (
    "color",
    "typography",
    "space",
    "radius",
    "shadow",
    "motion",
    "size",
    "breakpoint",
    "z",
)


# ------------------------------------------------------------------ contrast
def _lum(hex_colour: str) -> float:
    h = hex_colour.lstrip("#")
    channels = [int(h[i : i + 2], 16) / 255 for i in (0, 2, 4)]
    lin = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]


def contrast(a: str, b: str) -> float:
    hi, lo = sorted((_lum(a), _lum(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


# ------------------------------------------------------------------ css and tables
def css_variables(tokens: dict) -> dict[str, str]:
    return {
        f"--{group}-{name}": value for group in CSS_GROUPS for name, value in tokens[group].items()
    }


def render_css(tokens: dict) -> str:
    lines = [
        "/* GENERATED by tools/design.py --build from tokens.json. Do not edit by hand. */",
        ":root {",
    ]
    lines += [f"  {name}: {value};" for name, value in css_variables(tokens).items()]
    lines += ["}", "", "@media (prefers-reduced-motion: reduce) {", "  :root {"]
    lines += [
        f"    --motion-{name}: 0.01ms;" for name in tokens["motion"] if name.startswith("duration")
    ]
    lines += ["  }", "}", ""]
    return "\n".join(lines)


def render_reference(tokens: dict, status: dict, inv: dict) -> str:
    out = ["### Colour tokens and measured contrast", "", "| Token | Value |", "|---|---|"]
    out += [f"| `--color-{n}` | `{v}` |" for n, v in tokens["color"].items()]
    out += ["", "| Foreground on background | Ratio | Needed | Use |", "|---|---|---|---|"]
    for p in tokens["contrast_pairs"]:
        r = contrast(tokens["color"][p["fg"]], tokens["color"][p["bg"]])
        out.append(f"| `{p['fg']}` on `{p['bg']}` | {r:.2f}:1 | {p['min']}:1 | {p['use']} |")
    out += [
        "",
        "### Departures from MASTER.md",
        "",
        "| Token | Was | Now | Why (measured) |",
        "|---|---|---|---|",
    ]
    out += [
        f"| `{d['token']}` | {d['master']} | {d['value']} | {d['reason']} |"
        for d in tokens["deviations"]
    ]
    out += ["", "### Other tokens", "", "| Group | Tokens |", "|---|---|"]
    for group in CSS_GROUPS[1:]:
        out.append(
            f"| {group} | "
            + ", ".join(
                f"`--{group}-{n}`: `{v}`".replace("|", "/") for n, v in tokens[group].items()
            )
            + " |"
        )
    out += [
        "",
        "### Status vocabulary",
        "",
        "Shape and word are always shown together; tone is a hint.",
        "",
    ]
    for domain, states in status["domains"].items():
        out += [
            f"**{domain}**",
            "",
            "| State | Label | Shape | Tone | Meaning |",
            "|---|---|---|---|---|",
        ]
        out += [
            f"| `{k}` | {v['label']} | {v['shape']} | {v['tone']} | {v['meaning']} |"
            for k, v in states.items()
        ]
        out.append("")
    caps, screens = inv["capabilities"], inv["screens"]
    out += [
        "### Screens, capabilities and API",
        "",
        "| Screen | Capability (roles) | Required API | Optional by capability |",
        "|---|---|---|---|",
    ]
    for s in screens:
        cap = (
            f"`{s['capability']}` ({', '.join(caps[s['capability']]['roles'])})"
            if s["capability"]
            else "public"
        )
        out.append(
            f"| `{s['id']}` | {cap} | {', '.join('`' + a + '`' for a in s['api']) or '-'} | {', '.join('`' + a + '`' for a in s['optional_api']) or '-'} |"
        )
    return "\n".join(out) + "\n"


def splice(text: str, generated: str) -> str:
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n\n{generated}\n{END}{tail}"


# ------------------------------------------------------------------ backend enumerations
def sql_enum(migration: str, table: str, column: str) -> list[str]:
    sql = (MIGRATIONS / migration).read_text(encoding="utf-8")
    block = sql.split(f"CREATE TABLE {table} (", 1)[1].split("\n);", 1)[0]
    m = re.search(
        rf"{column}\s+text\s+NOT NULL\s+CHECK\s*\(\s*{column}\s+IN\s*\(([^)]*)\)", block, re.DOTALL
    )
    if m is None:
        raise ValueError(f"no CHECK IN list for {table}.{column} in {migration}")
    return re.findall(r"'([^']+)'", m.group(1))


def backend_enumerations() -> dict[str, set[str]]:
    freshness = json.loads(
        (SOURCE_ROOT / "contracts" / "signal-state" / "v1" / "schema.json").read_text(
            encoding="utf-8"
        )
    )["properties"]["freshness_status"]["enum"]
    return {
        "command": set(cmd_repo.ALLOWED_TRANSITIONS) | {"requested_policy_unavailable"},
        "recommendation": set(
            sql_enum("0005_incidents_recommendations.sql", "recommendations", "status")
        ),
        "outcome": set(out_repo.CLASSIFICATIONS),
        "incident": set(inc_repo.ALLOWED_TRANSITIONS),
        "severity": set(sql_enum("0005_incidents_recommendations.sql", "incidents", "severity")),
        "call": set(em_repo.CALL_TRANSITIONS),
        "assignment": set(em_repo.ASSIGNMENT_TRANSITIONS),
        "freshness": set(freshness),
        "device": set(sql_enum("0002_devices.sql", "devices", "status")),
        "truth": set(sql_enum("0006_emergency.sql", "emergency_calls", "truth_label")),
        "audit": set(sql_enum("0020_operator_workflows.sql", "operator_audit", "outcome")),
        "run": set(sql_enum("0009_scenario_control.sql", "scenario_runs", "status")),
    }


# ------------------------------------------------------------------ doc parsing
def component_sections(doc: str) -> dict[str, str]:
    body = doc.split("## Components", 1)[1].split("## Generated reference", 1)[0]
    parts = re.split(r"\n### ", "\n" + body)[1:]
    return {p.split("\n", 1)[0].strip(): p for p in parts}


def field(section: str, name: str) -> str | None:
    m = re.search(rf"- \*\*{re.escape(name)}\*\*: (.+)", section)
    return m.group(1) if m else None


def composition(doc: str) -> dict[str, list[str]]:
    body = doc.split("## Screen composition", 1)[1].split("## Components", 1)[0]
    out = {}
    for line in body.splitlines():
        m = re.match(r"\| `([a-z-]+)` \| (.+) \|$", line)
        if m:
            out[m.group(1)] = re.findall(r"`([A-Za-z]+)`", m.group(2))
    return out


def build() -> None:
    tokens, status, inv = (
        json.loads(p.read_text(encoding="utf-8")) for p in (TOKENS, STATUS, INVENTORY)
    )
    CSS.write_text(render_css(tokens), encoding="utf-8")
    DOC.write_text(
        splice(DOC.read_text(encoding="utf-8"), render_reference(tokens, status, inv)),
        encoding="utf-8",
    )
    print(f"wrote {CSS.name} and refreshed the generated reference in {DOC.name}")


def main() -> int:  # noqa: PLR0915
    if "--build" in sys.argv:
        build()
        return 0
    tokens, status, inv = (
        json.loads(p.read_text(encoding="utf-8")) for p in (TOKENS, STATUS, INVENTORY)
    )
    doc = DOC.read_text(encoding="utf-8")
    ev = Evidence("P08.03")

    ev.check(
        "tokens_css_is_exactly_what_tokens_json_generates",
        CSS.is_file() and CSS.read_text(encoding="utf-8") == render_css(tokens),
        detail="run tools/design.py --build",
    )
    ev.check(
        "the_generated_reference_tables_in_the_design_document_are_current",
        BEGIN in doc and splice(doc, render_reference(tokens, status, inv)) == doc,
        detail="run tools/design.py --build",
    )

    ratios = {
        f"{p['fg']} on {p['bg']}": round(
            contrast(tokens["color"][p["fg"]], tokens["color"][p["bg"]]), 2
        )
        for p in tokens["contrast_pairs"]
    }
    failing = {
        f"{p['fg']} on {p['bg']}": ratios[f"{p['fg']} on {p['bg']}"]
        for p in tokens["contrast_pairs"]
        if ratios[f"{p['fg']} on {p['bg']}"] < p["min"]
    }
    ev.check(
        "every_declared_colour_pair_meets_its_wcag_2_2_minimum",
        not failing,
        detail=str(failing) or f"{len(ratios)} pairs, lowest {min(ratios.values())}:1",
    )
    ev.metrics["contrast"] = {
        "pairs": ratios,
        "lowest": min(ratios.values()),
        "text_pairs_min_4_5": sum(1 for p in tokens["contrast_pairs"] if p["min"] == 4.5),
        "non_text_pairs_min_3": sum(1 for p in tokens["contrast_pairs"] if p["min"] == 3.0),
    }

    master = MASTER.read_text(encoding="utf-8")
    rows = {
        "Border": "Border",
        "Destructive": "Destructive",
        "Card": "Card",
        "Background": "Background",
        "Accent": r"Accent/CTA",
        "Ring": "Ring",
    }
    m = {
        key: "#" + re.search(rf"\| {re.escape(label)} \| `#([0-9A-Fa-f]{{6}})`", master).group(1)
        for key, label in rows.items()
    }
    claims = {
        "master border is below 3:1 on cards, so it cannot bound a control": contrast(
            m["Border"], m["Card"]
        )
        < 3.0,
        "master border is below 3:1 on the page, so it cannot bound a control": contrast(
            m["Border"], m["Background"]
        )
        < 3.0,
        "master destructive is below 4.5:1 on cards, so it cannot be error text": contrast(
            m["Destructive"], m["Card"]
        )
        < 4.5,
        "a lone white ring is below 3:1 on the accent button": contrast(m["Ring"], m["Accent"])
        < 3.0,
    }
    ev.check(
        "each_departure_from_master_md_is_justified_by_a_re_measured_failure",
        all(claims.values()),
        detail=str({k: v for k, v in claims.items() if not v}),
    )
    ev.metrics["master_measurements"] = {
        "border_on_card": round(contrast(m["Border"], m["Card"]), 2),
        "border_on_background": round(contrast(m["Border"], m["Background"]), 2),
        "destructive_on_card": round(contrast(m["Destructive"], m["Card"]), 2),
        "white_ring_on_accent": round(contrast(m["Ring"], m["Accent"]), 2),
    }

    enums, uncovered = backend_enumerations(), {}
    for domain, values in enums.items():
        missing = values - set(status["domains"].get(domain, {}))
        extra = set(status["domains"].get(domain, {})) - values
        if missing or extra:
            uncovered[domain] = {"missing": sorted(missing), "not_in_backend": sorted(extra)}
    ev.check(
        "every_backend_state_has_a_label_shape_and_tone_and_no_invented_states",
        not uncovered,
        detail=str(uncovered),
    )
    ev.metrics["status_coverage"] = {d: len(v) for d, v in enums.items()}
    bad_entries = [
        f"{d}.{k}"
        for d, states in status["domains"].items()
        for k, v in states.items()
        if not v["label"]
        or v["shape"] not in status["shapes"]
        or v["tone"] not in status["tones"]
        or not v["meaning"]
    ]
    ev.check(
        "every_status_entry_is_complete_and_uses_a_defined_shape_and_tone",
        not bad_entries,
        detail=str(bad_entries),
    )
    dupes = {}
    for d, states in status["domains"].items():
        shapes, labels = (
            [v["shape"] for v in states.values()],
            [v["label"] for v in states.values()],
        )
        if len(set(shapes)) != len(shapes) or len(set(labels)) != len(labels):
            dupes[d] = {
                "shapes": sorted({s for s in shapes if shapes.count(s) > 1}),
                "labels": sorted({s for s in labels if labels.count(s) > 1}),
            }
    ev.check(
        "no_two_states_of_a_lifecycle_share_a_shape_or_a_label_so_they_are_distinct_in_greyscale",
        not dupes,
        detail=str(dupes),
    )

    sections = component_sections(doc)
    token_names = set(css_variables(tokens))
    incomplete = {
        name: [f for f in REQUIRED_FIELDS if not field(sec, f)]
        for name, sec in sections.items()
        if any(not field(sec, f) for f in REQUIRED_FIELDS)
    }
    ev.check(
        "every_component_documents_purpose_anatomy_states_keyboard_aria_tokens_and_used_by",
        not incomplete and len(sections) >= 20,
        detail=str(incomplete) or f"{len(sections)} components",
    )
    screen_ids = {s["id"] for s in inv["screens"]}
    bad_refs = {}
    for name, sec in sections.items():
        toks = re.findall(r"`(--[a-z0-9-]+)`", field(sec, "Tokens") or "")
        screens = re.findall(r"`([a-z-]+)`", field(sec, "Used by") or "")
        errs = [f"unknown token {t}" for t in toks if t not in token_names] + [
            f"unknown screen {s}" for s in screens if s not in screen_ids
        ]
        if errs:
            bad_refs[name] = errs
    ev.check("every_token_and_screen_a_component_names_exists", not bad_refs, detail=str(bad_refs))
    comp = composition(doc)
    used_by = {
        name: set(re.findall(r"`([a-z-]+)`", field(sec, "Used by") or ""))
        for name, sec in sections.items()
    }
    problems = []
    if set(comp) != screen_ids:
        problems.append(
            f"composition screens differ from the inventory: {sorted(set(comp) ^ screen_ids)}"
        )
    for screen, comps in comp.items():
        for c in comps:
            if c not in sections:
                problems.append(f"{screen}: unknown component {c}")
            elif screen not in used_by[c]:
                problems.append(f"{screen} composes {c} but {c}'s Used by omits it")
    for c, screens in used_by.items():
        for s in screens:
            if c not in comp.get(s, []):
                problems.append(f"{c} says it is used by {s} but {s}'s composition omits it")
    for s in inv["screens"]:
        if s["live"] != ("LiveFeedStatus" in comp.get(s["id"], [])):
            problems.append(
                f"{s['id']}: a live screen shows LiveFeedStatus and a non-live screen does not (live={s['live']})"
            )
    unused = [c for c in sections if not any(c in cs for cs in comp.values())]
    if unused:
        problems.append(f"components no screen uses: {unused}")
    ev.check(
        "the_screen_composition_table_and_the_components_used_by_lists_agree_in_both_directions",
        not problems,
        detail="; ".join(problems[:3]),
    )
    ev.metrics["components"] = {
        "documented": len(sections),
        "screens_covered": len(comp),
        "tokens": len(token_names),
        "status_domains": len(status["domains"]),
        "status_states": sum(len(v) for v in status["domains"].values()),
    }
    return ev.finish()


if __name__ == "__main__":
    raise SystemExit(main())
